src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

Docker `1.3` and greater don't override a preexisting tag without the `-f` option.
This may create stale images:
```bash
> sbt docker:publishLocal
> docker images
docker-test         0.1.0               f2e7a5bb081e        About a minute ago   720 MB
docker-test         latest              f2e7a5bb081e        About a minute ago   720 MB
dockerfile/java     latest              e5b3ce7f0b79        4 days ago           705.7 MB
> sbt docker:publishLocal
> docker images
docker-test         0.1.0               49299e1e9e14        2 seconds ago        720 MB
docker-test         latest              49299e1e9e14        2 seconds ago        720 MB
<none>              <none>              f2e7a5bb081e        About a minute ago   720 MB
dockerfile/java     latest              e5b3ce7f0b79        4 …
```

Fixing update-latest to work with docker 1.3 and greater

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

PR https://github.com/sbt/sbt-native-packager/pull/424 moved to a ADD wildcard approach, and then removed the Dockerfile. There were two problems with this:
* ADD seems to behave weirdly regarding recursion. /opt/docker and /docker were both added to the output.
* I had incorrectly set the current working directory to the parent of the context directory, where it really should be the context directory itself. This only worked because there was a Dockerfile in the parent also.

Back to specific directory for ADD command

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-debian-template

This will only use PID file to check whether application is started or not. `--exec` in contrast is also checks the `/proc/[PID]/exe` file which links to the java executable and not original start script (see [this article](https://chris-lamb.co.uk/posts/start-stop-daemon-exec-vs-startas)). 
For more detail please see the discussion on #451
I tried to use another solution (`exec -a "appName"`), but unfortunately it does not work as I expected. So as far as i can tell `--startas` is the only option.

Using `--startas` instead of `--exec` now in order to make start script idempotent.

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-debian-template
src/main/scala/com/typesafe/sbt/packager/linux/Keys.scala
src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala
src/sbt-test/debian/sysvinit-stoptimeouts-deb/build.sbt
src/sbt-test/debian/sysvinit-stoptimeouts-deb/project/plugins.sbt
src/sbt-test/debian/sysvinit-stoptimeouts-deb/test

start-stop-dameons does not wait for service to stop before returning.
This may results in error on upgrade of the package trying to start the service while old version is still shutting down.

wait for process to stop or timeout in systemv init script

---

README.md

The replaced link doesn't appear to exist in the docs anymore.  Replaced with current valid link to Docker Plugin section.

Fix broken link to Docker help.

---

src/main/resources/com/typesafe/sbt/packager/archetypes/bash-template
src/main/resources/com/typesafe/sbt/packager/archetypes/etc-default-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-debian-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-rpm-template
src/sphinx/archetypes/java_server/customize.rst

Simply use wildly used JAVA_OPTS envars to set exec parameters.
I don't know how to tests this :/
BTW tests passes on unversal and debian

[fix #472] /etc/default/<package-name> should be shell script setting envars

---

src/main/resources/com/typesafe/sbt/packager/archetypes/bash-template

When providing the -jvm-debug flag the sbt native packager's bash template currently passes the following jvm debug flags:
-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=[debug port]
This is outdated (it is for JVM 1.4.x) and for newer JVMs should be:
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=[debug port]

[Fix #476] Fixing -jvm-debug flags so that they use args compatible with the latest JDKs

---

.travis.yml
build.sbt
src/main/scala/com/typesafe/sbt/packager/FileUtil.scala
src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala
src/main/scala/com/typesafe/sbt/packager/universal/Keys.scala
src/main/scala/com/typesafe/sbt/packager/universal/UniversalPlugin.scala
src/main/scala/com/typesafe/sbt/packager/universal/ZipHelper.scala
src/sbt-test/universal/test-zips-no-top-level-dir/build.sbt
src/sbt-test/universal/test-zips-no-top-level-dir/project/plugins.sbt
src/sbt-test/universal/test-zips-no-top-level-dir/src/universal/conf/test
src/sbt-test/universal/test-zips-no-top-level-dir/test
src/sphinx/formats/universal.rst
src/test/scala/com/typesafe/sbt/packager/DeleteDirectoryVisitor.scala
src/test/scala/com/typesafe/sbt/packager/FileUtilSpec.scala
src/test/scala/com/typesafe/sbt/packager/universal/ZipHelperSpec.scala
test-project-simple/project/build.properties

In favor of #142
Java 7 couldn't help in preserving the file permissions. Still some of the Process calls
were removed, which should bring a performance and compatibility benefit. 
This pull request will require users to use at least java 7 for their builds.

Upgrading to java 7 and using posix nio API

---

README.md
src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerHelper.scala
src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerKeys.scala
src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerPlugin.scala
src/sphinx/formats/index.rst
src/sphinx/formats/jdkpackager.rst
test-project-jdkpackager/build.sbt
test-project-jdkpackager/src/main/scala/ExampleApp.scala
test-project-jdkpackager/src/universal/conf/jvmopts

Added this so standard JVM options encoded in the `con/jvmopts` file are translated and passed on to `javapackager`.

Added translation of `jvmopts` contents and enhanced example app.

---

.travis.yml
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaApp.scala
src/main/scala/com/typesafe/sbt/packager/jar/ClasspathJarPlugin.scala
src/main/scala/com/typesafe/sbt/packager/jar/LauncherJarPlugin.scala
src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerHelper.scala
src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerPlugin.scala
src/sbt-test/jar/launcher-jar/build.sbt
src/sbt-test/jar/launcher-jar/project/plugins.sbt
src/sbt-test/jar/launcher-jar/src/main/scala/test/Test.scala
src/sbt-test/jar/launcher-jar/src/templates/bat-template
src/sbt-test/jar/launcher-jar/test
src/sphinx/topics/index.rst
src/sphinx/topics/longclasspath.rst

The launcher jar plugin generates a jar with a classpath and main class in the manifest.
Also refactored the classpath jar plugin to use standard sbt ways of building jars, and to depend on the scriptClasspath so that projects that modify it (such as Play) will still work with it.

Added launcher jar plugin

---

src/main/scala/com/typesafe/sbt/packager/rpm/RpmMetadata.scala
src/main/scala/com/typesafe/sbt/packager/windows/WixHelper.scala

This should not be a functional change. It is just some of recommended clean up from https://www.codacy.com/public/nepomukseiler/sbt-native-packager/dashboard
I was just snooping and figured, might as well fix a couple.

Codacy recommended cleanup.

---

src/sphinx/formats/rpm.rst

I believe this is what was meant to be said. To see what's on master as it is now see: http://www.scala-sbt.org/sbt-native-packager/formats/rpm.html?highlight=template#scriptlet-changes
It doesn't look correct to me.

Fix incorrect information in RPM Plugin docs.

---

src/main/scala/com/typesafe/sbt/packager/archetypes/JavaApp.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppKeys.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala

Added the possibility to create a configuration file to be sourced before running the app.

Added support for environment configuration file.

---

src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala
src/sphinx/formats/rpm.rst

- `name in Rpm` is not actually used, instead it is the `packageName in Rpm` setting that is relevant.
- describe the relations between sbt settings and the rpm file name
- describe the relations between sbt settings and the rpm spec file
- remove listings of settings that are not in fact required settings
- change default value of `rpmRelease` from `0` to `1`

Improvements to RPM documentation

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-debian-template

Avoid complex logic with unhandled corner cases. If a process has
crashed leaving an invalid PID file behind, the current logic does
not remove the invalid PID file, although the process is not running.

Fix #531: Simplify stop() function on Debian based systems.

---

src/main/scala/com/typesafe/sbt/packager/rpm/Keys.scala
src/main/scala/com/typesafe/sbt/packager/rpm/RpmMetadata.scala
src/sphinx/formats/rpm.rst

- fix and improve sbt setting descriptions
- remove TODO originating in d0ae3a2
- expand on site documentation for these settings

Fix and improve docs for rpmAutoreq and rpmAutoprov

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

according to https://blog.docker.com/2015/03/updates-available-to-popular-repos-update-your-images/, all dockerfile/* repos will be replaced with an official repository. This may be a better default configuration.

!Update default dockerBaseImage to official repo

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/rpm/preun-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/loader-functions

- update rpm preun-template to match the rpm postinst-template by making use of the `stopService` loader function
- make systemv loader-functions consistent in use of `hash` builtin and redirections, and tidy up language in warning message

make use of stopService loader function in rpm preun template

---

src/sphinx/archetypes/cheatsheet.rst

- document where the values for these template vars are sourced from
- fill in the missing vars: version, daemon_user_uid, daemon_group, daemon_group_id, daemon_shell, term_timeout, kill_timeout, start_facilities, stop_facilities, start_runlevels, stop_runlevels
- remove app_main_class and app_classpath, which are no longer valid vars

expand the doc for the start script template vars

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-rpm-template

It looks like a bug was introduced in commit 22a691a582506b444e794b0657c9382e7e8ca236, where if `executableScriptName in Linux` and `packageName in Linux` are not equal, then an incorrect script is generated.
The `exec` template variable should only be used to build the run command. Everything else should be the `app_name`.

fix use of app_name and exec vars in systemv start-rpm-template

---

src/main/resources/com/typesafe/sbt/packager/archetypes/etc-default-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-rpm-template

Main fix is to make use of the `daemon` library function in `start`, correcting broken invocation of `runuser`.
For processes that manage their own pid file, they should define the `PIDFILE` variable (sourced either through `/etc/default/…` or `/etc/sysconfig/…`). Otherwise, if undefined, this script will capture the pid and write it to `/var/run/${{app_name}}/running.pid`.
Other minor changes:
- don’t need to call `success`/`failure` in `start` as this is already done by `daemon`
- don’t need to create `/var/run/${{app_name}}` dir as this is already done by the linux package mappings and thus the dir is created at package install time.

fix SystemV init script template for rpm packaging

---

.travis.yml

Enable container architecture and caching
> The features described here are currently only available for private repositories on travis-ci.com and our new container-based infrastructure. These features are also still experimental, please contact us with any questions, issues and feedback.
- http://docs.travis-ci.com/user/caching/
- [Arbitrary Directories](http://docs.travis-ci.com/user/caching/#Arbitrary-directories)
- [Ubuntu Packages](http://docs.travis-ci.com/user/caching/#Caching-Ubuntu-packages)

Trying travis-ci container architecture for faster builds.

---

.travis.yml

- silence info-level logging for dependency resolving and downloading in update
- split tasks for update, compile, test:compile, so that sbt will show task completion times for each
- join test and scripted tasks into one sbt invocation
- use bash && so that failure stops the build

Optimize Travis script

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-rpm-template
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala
src/sbt-test/rpm/test-executableScriptName/build.sbt
src/sbt-test/rpm/test-packageName/build.sbt

- fix warning from start script about [lockfile name](https://github.com/matwey/rpmlint/blob/67aec2b86e24d67b0674f4a0a17ac9f9c76ba736/InitScriptCheck.py#L256)
- don’t mark SystemV init script as `%config`

Fix warnings from rpm lint

---

src/main/scala/com/typesafe/sbt/packager/FileUtil.scala
src/main/scala/com/typesafe/sbt/packager/universal/ZipHelper.scala
src/main/scala/com/typesafe/sbt/packager/windows/WixHelper.scala
src/test/scala/com/typesafe/sbt/packager/FileUtilSpec.scala

To remove the use of deprecated (in Scala) octal literals, took the approach of parsing octal strings via a string interpolator, in line with this SO on the issue:
http://stackoverflow.com/questions/16590236/scala-2-10-octal-escape-is-deprecated-how-to-do-octal-idiomatically-now/16591277#16591277

Compilation warning cleanup, including removal of deprecated octal literals.

---

src/sphinx/formats/docker.rst

I found out the hard way that putting `dockerExposedPorts in Docker := Seq(9000, 9443)` into your build.sbt does nothing. The correct setting is `dockerExposedPorts := Seq(9000, 9443)`. I believe the docs, as they are, are misleading.

Remove `in Docker` from dockerExposedPorts in docs

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

When native-packager add a folder in Dockerfile, it uses "File.separator" but this add doesn't depend to context of build.

Use docker on windows #573

---

src/sphinx/formats/linux.rst

Documented the `packageTemplateMappings` helper that allows to add empty directories to the mappings.

Documented packageTemplateMappings

---

src/main/scala/com/typesafe/sbt/packager/MappingsHelper.scala

documented in scaladoc for now

FIX #347 add ability to add arbitrary stuff from the classpath. Only

---

src/sphinx/topics/play.rst

As discussed on the Gitter channel.

Correct the way to give additional informations for Play apps

---

src/sphinx/topics/deployment.rst

As far as i understand this is the proper way of deploying universal packages. If not, then ignore ;-)

Deployment section, documentation fix

---

src/sphinx/topics/deployment.rst

another docs PR - currently the old way of adding ``deploymentSettings`` is mentioned in the docs, while it's already deprecated

use autopluging system in deployments docs

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemd/start-template

CentOS 7 and many other recent Linuxes have switched to a non-persistent (tmpfs) /run folder, with /var/run being a symbolic link to the tmpfs /run mount.  The RPM creates the correct folder in /var/run for the PID file, but on reboot, that file is gone.  There are many ways to fix it.  This way will work on older systemd versions.
This change was tested on CentOS 7.

If the /var/run (aka /run) folder doesn't exist for the PID file, create it

---

src/main/scala/com/typesafe/sbt/packager/docker/dockerfile.scala

Added EnvCmd to add `ENV` to your Dockerfile since it differs a bit from default Cmd syntax.

Added EnvCmd

---

src/main/scala/com/typesafe/sbt/packager/docker/dockerfile.scala

I added `CombinedCmd` for `ONBUILD` instruction and possible future commands that will be added that will have a similar form. For readability I made it so that it uses a `CmdLike` object as an argument. `Cmd` could also be used with an extra argument but it would degrade readability. Removed `EnvCmd` because it introduced an inconsistency in the API with `ADD` and `COPY`. Made `Cmd` accept multiple arguments because this solves the `ADD` and `ENV` inconsistency. This fix won't break the old API because a string with a space in the middle is still acceptable only less readable.

Added CombinedCmd and removed EnvCmd

---

src/main/resources/com/typesafe/sbt/packager/linux/control-functions

`--no-create-home` is a default option for system users. I removed it because it's not supported on CentOS.

FIX #621 --system option for user/groupadd replaced with -r.

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemd/start-template

Update start-template for systemd

---

src/main/scala/com/typesafe/sbt/packager/archetypes/JavaApp.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppKeys.scala
src/sbt-test/bash/override-templates/build.sbt
src/sbt-test/bash/override-templates/custom-templates/custom-bash-template
src/sbt-test/bash/override-templates/custom-templates/custom-bat-template
src/sbt-test/bash/override-templates/project/plugins.sbt
src/sbt-test/bash/override-templates/src/main/scala/MainApp.scala
src/sbt-test/bash/override-templates/test
src/sphinx/archetypes/java_app/customize.rst

This implements feature request #635. 
I left the old method signatures in the [`JavaAppStartScript`](https://github.com/sbt/sbt-native-packager/blob/6cd1c3a04591dba721ea7e022c5d98c1230bbc7d/src/main/scala/com/typesafe/sbt/packager/archetypes/JavaApp.scala#L282) trait, for backwards compatibility. Is this something that you could use? Should I add an example test project demonstrating this feature?

overridable bash and bat templates

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/rpm/postinst-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/rpm/postun-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/rpm/preinst-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/rpm/preun-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemd/loader-functions
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/loader-functions
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/upstart/loader-functions

I have encountered a problem that a systemd appplication packaged to rpm does not restart after installing a new version. So, I made changes in the bash scripts included in the rpm - I made use of already made  [systemd macros] (http://cgit.freedesktop.org/systemd/systemd/tree/src/core/macros.systemd.in)

Improved rpm scripts for systemd

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/rpm/preinst-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-rpm-template

Save the value of `RPM_INSTALL_PREFIX` into application's sysconfig file.
Upon application start up, look for this value, else use the `chdir` value supplied via sbt templates.
--
I have two options in detecting where the RPM package is installed.
**Option 1: Use `RPM_INSTALL_PREFIX` provided during installation process**
The `RPM_INSTALL_PREFIX` environment variable is only provided during the install time. This value would need to be persisted so it can be retrieved during application start-up.
**Option 2: Use rpm command**
The command `rpm -q --queryformat "%{INSTPREFIXES}" ${{app_name}}` will print out the location where the package is installed. This command works for both Redhat 6 and 7.
I have decided to go with Option 1 because we are using the values provided to us by the …

Support for relocatable RPMs

---

build.sbt
src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/DockerSpotifyClientPlugin.scala
test-project-docker/build.sbt

Handle #558 only for `publishLocal`.
`publish` is a little bit complex as it requires to handle push to private repositories and credentials.

Use spotify docker-client for docker:publishLocal goal

---

src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala
src/main/scala/com/typesafe/sbt/packager/universal/Keys.scala
src/main/scala/com/typesafe/sbt/packager/universal/UniversalPlugin.scala
src/sphinx/formats/universal.rst

FIX #662 and make universal archive options customizable

---

src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala

The methods in question are the methods used to create various kinds of archives (e.g. zip or tar) from `com.typesafe.sbt.packager.universal.Archives`

WIP - DON'T MERGE - Reinstate and deprecate older methods to preserve binary backward compatibility with 1.0.4

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/rpm/preinst-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-rpm-template
src/sbt-test/rpm/sysvinit-rpm/build.sbt

The fixes address the following issues.
**Ensure RPM preinst script continues normally when `rpmPrefix` is not declared**
Without this fix, when `rpmPrefix` is not declared, the `preinst` will terminate in error.
**Ensure application is running on the installed directory in the RPM-based distribution**
This was fixed as part of PR #653 which was accidentally removed in PR #661. Tests are added to prevent this regression from occurring.

Fixes for RPM related functionality in 1.0.5-M2

---

src/sphinx/formats/rpm.rst

Currently rpm-build is a requirement of the rpm format aswell, it will fail hardly if you don't have it installed.

Added rpm-build as a Requirement for *.rpm

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-rpm-template

On CentOS 7 /run is tmpfs, and /var/run is a symlink to /run.
Upon reboot the /var/run/${{app_name}} directory (created by the RPM)
will be blown away, causing the init script to fail - but still spawn
the service as a side effect.
This change will create the /var/run/${{app_name}} directory if it does
not already exist, and change the owner to $DAEMON_USER.

Ensure pidfile dir on systemv rpm template exists

---

src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala
src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala
src/main/scala/com/typesafe/sbt/packager/rpm/RpmHelper.scala
src/main/scala/com/typesafe/sbt/packager/rpm/RpmMetadata.scala
src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala
src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala
src/sbt-test/jar/classpath-jar/src/main/scala/test/Test.scala
src/sbt-test/rpm/scriptlets-rpm/build.sbt

When creating relocatable RPM packages, the symlink needs to take into account the relocated file paths.
RPM does not provide out of the box support for this, hence the pull request to manage symlinks as part of `%post` and `%postun` scriptlet. This will ensure the symlink will be created and removed as part of post-install and post-uninstall step.
When creating the symlink, both the source path and the symlink itself need to take into account the relocated path.

Relocatable rpm symlink fix

---

src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala
src/main/scala/com/typesafe/sbt/packager/linux/Keys.scala

This allows to add "@" to the script name which is useful when using systemd. Any unit name containing "@" in name is used as template unit which allows to create multiple units from single start script. More information: https://wiki.archlinux.org/index.php/Systemd (in section "Using units" -> "Note")

Allow to override systemd start script name

---

build.sbt

Using the spotify docker client in Play 2.4.x projects leads to jackson errors like :
```[error] (docker:publishLocal) com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.lang.AbstractMethodError: com.fasterxml.jackson.jaxrs.base.ProviderBase._configForReading(Lcom/fasterxml/jackson/databind/ObjectReader;[Ljava/lang/annotation/Annotation;)Lcom/fasterxml/jackson/jaxrs/cfg/EndpointConfigBase;```
Upgrading to 3.2.1 fixes it.

Upgrade spotify docker-client to 3.2.1

---

src/main/resources/com/typesafe/sbt/packager/archetypes/etc-default-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-debian-template
src/sphinx/topics/play.rst

For processes that manage their own pid file, they should define the `PIDFILE` variable (sourced either through `/etc/default/…` or `/etc/sysconfig/…`). Otherwise, if undefined, this script will capture the pid and write it to `/var/run/${{app_name}}/running.pid`.
This commit is related to https://github.com/sbt/sbt-native-packager/commit/45bc5dbaffdca8eaef4b498c6b93e3e03350428d that implements the same logic for rpm packaging

fix SystemV init script template for debian packaging

---

src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala
src/sbt-test/debian/override-start-script/build.sbt
src/sbt-test/debian/override-start-script/project/plugins.sbt
src/sbt-test/debian/override-start-script/src/templates/debian/systemv
src/sbt-test/debian/override-start-script/src/templates/debian/upstart
src/sbt-test/debian/override-start-script/src/templates/start
src/sbt-test/debian/override-start-script/test
src/sphinx/archetypes/cheatsheet.rst
src/sphinx/archetypes/java_server/customize.rst

The reason is that somebody may want to build rpm with customized systemV script and deb with default upstart script.

Different start script replacements for different system loaders

---

src/main/resources/com/typesafe/sbt/packager/archetypes/ash-template

AshScriptPlugin - pass arguments loaded from script conf file

---

src/sphinx/topics/deployment.rst

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sbt/sbt-native-packager/708)

Improve docs on deploying different pkg formats

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemd/loader-functions
src/sbt-test/rpm/systemd-rpm/build.sbt
src/sbt-test/rpm/systemd-rpm/test

Ensure correct installation path is being used in the service file required by systemd.
This is done by replacing the default installation path with the actual installation path
within the service file during install time of the RPM package.

Ensure systemd works with RPM relocatable packages

---

.travis.yml
sbt

Travis: build on OS X (take 2)

---

build.sbt
src/main/scala/com/typesafe/sbt/packager/docker/DockerSpotifyClientPlugin.scala
src/sbt-test/debian/jdeb-dependencies/project/plugins.sbt
src/sbt-test/debian/jdeb-dir-mappings/project/plugins.sbt
src/sbt-test/debian/jdeb-script-replacements/project/plugins.sbt
src/sbt-test/debian/override-start-script/project/plugins.sbt
src/sbt-test/debian/simple-jdeb/project/plugins.sbt
src/sbt-test/docker/spotify-client/build.sbt
src/sbt-test/docker/spotify-client/project/plugins.sbt
src/sbt-test/docker/spotify-client/src/main/scala/Main.scala
src/sbt-test/docker/spotify-client/test
src/sphinx/formats/debian.rst
src/sphinx/formats/docker.rst
test-project-docker/project/plugins.sbt
test-project-simple/project/plugins.sbt

Follow up to the discussion in #693
- java-based packaging alternatives dependencies are marked as `provided`
- less dependencies per default, faster builds, less dependency conflict potential

Mark docker and jdeb as provided dependencies

---

.travis.yml
build.sbt

Changing `jdeb` to a provided dependency removed the `ant` dependency from the runtime  classpath, which is needed for the `jdkpackager` plugin.
Adding travis tests and dependency.

Adding ant dependency for jdkpackager builds. Follow up to #719

---

README.md

Since sbt-native already provides a DockerPlugin, many people get confused as to the difference between the one included in sbt-native and the `sbt-docker` one linked on the homepage.  The question has come up several times in gitter.

Docker Plugin qualification

---

archetypes/index.html

Was introduced in 78611a323cf8177791ea9469ad162e5a603d8678.

Fix typo (enablePlugis → enablePlugins)

---

.gitignore
src/main/resources/com/typesafe/sbt/packager/archetypes/etc-default-systemd-template
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemd/start-template
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppKeys.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala
src/sbt-test/debian/override-etc-default/build.sbt
src/sbt-test/debian/override-etc-default/project/plugins.sbt
src/sbt-test/debian/override-etc-default/src/templates/etc-default
src/sbt-test/debian/override-etc-default/test
src/sbt-test/debian/systemd-deb/build.sbt
src/sbt-test/debian/systemd-deb/test
src/sphinx/archetypes/cheatsheet.rst
src/sphinx/archetypes/java_server/customize.rst
src/sphinx/archetypes/java_server/my-first-project.rst

This change modifies the SystemD template to include the packaged
/etc/default environment settings file. Since a sourced SystemD
environment file is not the same thing as a bourne shell source script,
a different template is used.
Those deploying their package to multiple platforms can also specify
different /etc/default templates by suffixing `-systemd` to their name,
ie: src/templates/etc-default-systemd

SystemD services now source /etc/default/{{app_name}} (resolves #737)

---

build.sbt
src/main/scala/com/typesafe/sbt/packager/docker/DockerSpotifyClientPlugin.scala
src/sbt-test/docker/spotify-client/project/plugins.sbt
src/sphinx/formats/docker.rst
test-project-docker/project/plugins.sbt

NullPointerException is appeared, when i try to build & publish an image to a local Docker Registry at first time (after clean):
[info] PublishLocal using Docker API 1.22
[info] Step 1 : FROM lwieske/java-8:jre-8u72-slim
[trace] Stack trace suppressed: run last server/docker:publishLocal for the full output.
[error] (server/docker:publishLocal) java.lang.NullPointerException
[error] Total time: 154 s, completed Mar 3, 2016 1:25:22 PM
> last server/docker:publishLocal
[info] PublishLocal using Docker API 1.22
[info] Step 1 : FROM lwieske/java-8:jre-8u72-slim
java.lang.NullPointerException
at sbt.ConsoleLogger.log(ConsoleLogger.scala:195)
at sbt.ConsoleLogger.log(ConsoleLogger.scala:185)
at sbt.AbstractLogger.log(Logger.scala:28)
at …

Updates version of DockerSpotifyClient to 3.5.13 and fixes NullPointerException

---

src/main/resources/com/typesafe/sbt/packager/archetypes/bat-template

Without double quotes the path with paranthesis gets evaluated causing an error on Windows systems. Specifically the error text is "\\\.. was unexpected at this time."
I got the error when I moved my Play distro inside a Dropbox folder with name "Dropbox (COMPANYNAME)". The path (COMPANYNAME) part gets evaluated as the if condition clause and makes the batch throw the error above and close. 
Double quoting the %CFG_FILE% variable seems to be fixing the error.

Fix errors when .bat file path contains paranthesis.

---

src/sphinx/archetypes/java_app/customize.rst

Add a hint for Window-users that the bat.script expects the configuration on the differnt place and in a differnt way
https://github.com/sbt/sbt-native-packager/issues/768#issuecomment-207745671

Add hint for windows-users (configuration)

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

Make Docker plugin portable so that Windows is supported

---

src/main/scala/com/typesafe/sbt/packager/debian/DebianPlugin.scala
src/main/scala/com/typesafe/sbt/packager/debian/Keys.scala
src/main/scala/com/typesafe/sbt/packager/debian/NativePackaging.scala
src/sbt-test/debian/native-build-compress/build.sbt
src/sbt-test/debian/native-build-compress/project/plugins.sbt
src/sbt-test/debian/native-build-compress/test
src/sbt-test/debian/native-build-default/build.sbt
src/sbt-test/debian/native-build-default/project/plugins.sbt
src/sbt-test/debian/native-build-default/test
src/sphinx/formats/debian.rst

Representative example:
A Play project takes 30 seconds for `dpkg-deb` to build a 70MB deb with compression.
The same project takes 1 second to build a 79MB deb without compression.
Since JARs are already compressed archives, a sensible default is to not compress them again. (In fact, I'd be surprised if the small gains in client downloads weren't almost entirely overcome by the time to decompress.)
Users can use `debianNativeBuildOptions` to override options for `dpkg-deb` if they would like a different compression type, level, etc.

Don't compress debian packages

---

src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-debian-template

An `if` construct was not properly closed by `fi` which led to errors
when trying to start the system service.

Fix typo in debian systemv script.

---

src/main/scala/com/typesafe/sbt/packager/debian/DebianMetadata.scala
src/main/scala/com/typesafe/sbt/packager/debian/DebianPlugin.scala
src/main/scala/com/typesafe/sbt/packager/debian/Keys.scala
src/sbt-test/debian/jdeb-conflicts/build.sbt
src/sbt-test/debian/jdeb-conflicts/project/plugins.sbt
src/sbt-test/debian/jdeb-conflicts/test
src/sbt-test/debian/jdeb-provides/build.sbt
src/sbt-test/debian/jdeb-provides/project/plugins.sbt
src/sbt-test/debian/jdeb-provides/test
src/sbt-test/debian/simple-deb/build.sbt
src/sbt-test/debian/simple-jdeb/build.sbt
src/sphinx/formats/debian.rst

includes changes to code, tests and docs
Fixes #801

Support for 'Provides' and 'Conflicts' sections for debian packaging

---

src/main/scala/com/typesafe/sbt/packager/windows/Keys.scala
src/main/scala/com/typesafe/sbt/packager/windows/WindowsPlugin.scala
src/main/scala/com/typesafe/sbt/packager/windows/WixHelper.scala
src/sphinx/formats/windows.rst
test-project-windows/build.sbt
test-project-windows/project/build.properties
test-project-windows/project/plugins.sbt
test-project-windows/src/main/scala/ExampleApp.scala
test-project-windows/src/templates/etc-default-template

…4 by default but can be overridden by user.
Fixes issue #780 and allows using the newest Wix toolset.

Introduce new namespace and solve duplicate key issue

---

src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemdPlugin.scala
src/sbt-test/debian/systemd-deb/build.sbt
src/sbt-test/debian/systemd-deb/test
src/sphinx/archetypes/systemloaders.rst

Use recommended path for systemd scripts

---

src/sphinx/formats/debian.rst

As requested by @muuki88 in comments of commit cee091c

Report compression issue with Debian Wheezy's python-apt

---

src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala
src/sbt-test/rpm/scriptlets-override-rpm/build.sbt
src/sbt-test/rpm/scriptlets-override-rpm/test

Fix incorrect logic when detecting processed RPM scriptlets override file.
Includes cherry-picked test from #819.
Fixes #812.

Fix duplicate RPM scriptlet override

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

Closes #823
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sbt/sbt-native-packager/824)

Make `sbt docker:stage` work on Windows

---

src/main/resources/com/typesafe/sbt/packager/archetypes/bash-template
src/sbt-test/bash/java-home-var-expansion/build.sbt
src/sbt-test/bash/java-home-var-expansion/project/plugins.sbt
src/sbt-test/bash/java-home-var-expansion/src/main/scala/MainApp.scala
src/sbt-test/bash/java-home-var-expansion/test
src/sphinx/archetypes/java_app/index.rst
src/sphinx/recipes/embedded-jvm.rst
src/sphinx/recipes/index.rst

This PR is related to #816 and it changes the bash launcher to expand variables inside the `java-home` variable. This lets you build self-contained tarballs that contain the jre and use it to launch the application
With this PR you can define, e.g.
`-java-home ${app_home}/../jre` and the `app_home` variable will be resolved
A test is included, execute with
```
scripted bash/java-home-override
```
The updated launcher has been tested with bash 3.2.7 in OSX and bash 4.1.2 in CentOS 6
If this is accepted I would provide documentation for the website too

Expand the java home argument

---

src/sphinx/archetypes/java_server/customize.rst

I had to look it up in the source code..

maintainer file names were missing

---

src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemd/start-template
src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemdPlugin.scala
src/sbt-test/debian/systemd-deb/build.sbt
src/sbt-test/rpm/systemd-rpm/build.sbt
src/sphinx/archetypes/systemloaders.rst

You can now add the `ExitSuccessStatus` as a setting
```scala
enablePlugins(JavaAppPackaging, SystemdPlugin)
// for rpm
systemdSuccessExitStatus in Rpm += Seq("143")
// for deb
systemdSuccessExitStatus in Debian += Seq("143")
```

FIX #770 add ExitStatusSuccess setting for systemd

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

fixes #818, #838 in the 1.1.x branch

docker: tag -f is deprecated (backport to 1.1.x)

---

src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-debian-template

As already corrected in 1.2.x - https://github.com/sbt/sbt-native-packager/commit/a1d6023d29eccbf11e24e05de0d76bc4434c7170

Fix typo in debian systemv script

---

src/main/resources/com/typesafe/sbt/packager/archetypes/ash-template

The bash-template correctly correctly wraps the `java` entrypoint in `exec`:
https://github.com/sbt/sbt-native-packager/blob/73cc27a920b8162fa55dafc4897acd160707837e/src/main/resources/com/typesafe/sbt/packager/archetypes/bash-template#L249-L255
https://github.com/sbt/sbt-native-packager/blob/73cc27a920b8162fa55dafc4897acd160707837e/src/main/resources/com/typesafe/sbt/packager/archetypes/bash-template#L136
however here it was missing.
This causes issues when using Docker, because exit signals are not
passed onto the java process, so e.g. Ctrl-C doesn't stop
the running application.
See here for details on why this is needed in Docker:
https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example

Fix: `exec` the java entrypoint in ash-template

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/DockerSpotifyClientPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/sbt-test/docker/tag/build.sbt
src/sbt-test/docker/tag/project/plugins.sbt
src/sbt-test/docker/tag/src/main/scala/Main.scala
src/sbt-test/docker/tag/test
src/sphinx/formats/docker.rst

Using `SettingKey` instead of `TaskKey` for the `dockerTag` setting.
The `dockerTarget` configuration is used as Docker tag and was not documented yet. Renaming it to a more applicable name.

Rename dockerTarget to dockerTag

---

src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala
src/sbt-test/rpm/simple-rpm/build.sbt
src/sbt-test/rpm/simple-rpm/test

This change updates the RPM plugin settings so that keys starting with `rpm` are no longer scoped to the `Rpm` configuration. This should address #789.
I didn't see a formal testing process documented (though I may have missed it in the docs), so far I've only verified that `sbt test` and `sbt scripted rpm/*` are passing (both ran on a VM running centos7).
TODO

Fix scoping in RPM plugin for #789

---

src/sphinx/introduction.rst

I've started to learn and use sbt-native-packager.  The documentation has been a great help.
I've gone through the Introduction and corrected some grammar mistakes and also strengthened and clarified some places.
This is PR covers just the Introduction page because I didn't want to do too much work before checking to see what was actually wanted and needed.  I also didn't squash my commits in case you wanted to review my reasons for each change.  (But I can certainly squash them if that's what's wanted.)
If this is helpful, I can do some more sections.

Introduction:  clarify and fix grammar

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/override-commands/build.sbt
src/sphinx/formats/docker.rst

As per https://hub.docker.com/_/java/ the default `java` images have been deprecated in favor of `openjdk` (https://hub.docker.com/_/openjdk/) and will no longer receive updates after this year.
This change is replacing the references to `java:latest` with `openjdk:latest` both in code and documentation.

Replace deprecated java Docker image with openjdk

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/sbt-test/docker/ports/build.sbt
src/sbt-test/docker/ports/test
src/sphinx/formats/docker.rst

Add `dockerExposedUdpPorts` similar to the existing `dockerExposedPorts`.
Note that this depends on #880 for the tests to pass.
Fixed #843

Add ability to expose UDP ports

---

src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppAshScript.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppBashScript.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppBatScript.scala
src/sbt-test/bash/absolute-path-in-bash/build.sbt
src/sbt-test/bash/absolute-path-in-bash/project/plugins.sbt
src/sbt-test/bash/absolute-path-in-bash/src/main/scala/MainApp.scala
src/sbt-test/bash/absolute-path-in-bash/test
src/sbt-test/universal/absolute-path/build.sbt
src/sbt-test/universal/absolute-path/project/plugins.sbt
src/sbt-test/universal/absolute-path/src/main/scala/MainApp.scala
src/sbt-test/universal/absolute-path/test
src/sbt-test/windows/absolute-path-in-bat/build.sbt
src/sbt-test/windows/absolute-path-in-bat/project/plugins.sbt
src/sbt-test/windows/absolute-path-in-bat/src/main/scala/MainApp.scala
src/sbt-test/windows/absolute-path-in-bat/test

Do not prefix with $lib_dir when an absolute path is added to the
classpath

Support for absolute paths in classpath

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/udp-only-ports/build.sbt
src/sbt-test/docker/udp-only-ports/project/plugins.sbt
src/sbt-test/docker/udp-only-ports/test

Right now setting
```
dockerExposedPorts := Seq()
dockerExposedUdpPorts := Seq(10000, 10001)
```
would not generate EXPOSE section

Generate EXPOSE when only UDP ports are exposed

---

src/sphinx/formats/universal.rst

Includes an example (that seems to be working for me).
I'm completely unfamiliar with Sphinx neither an Sbt expert, so please forgive me if this is wrong in either substance or format.

Update documentation with warning about overriding default tar options.

---

src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemVPlugin.scala
src/sbt-test/rpm/override-start-script-systemd/build.sbt
src/sbt-test/rpm/override-start-script-systemd/project/plugins.sbt
src/sbt-test/rpm/override-start-script-systemd/src/templates/start
src/sbt-test/rpm/override-start-script-systemd/src/templates/systemloader/systemd
src/sbt-test/rpm/override-start-script-systemd/test
src/sbt-test/rpm/override-start-script-systemv/build.sbt
src/sbt-test/rpm/override-start-script-systemv/project/plugins.sbt
src/sbt-test/rpm/override-start-script-systemv/src/templates/start
src/sbt-test/rpm/override-start-script-systemv/src/templates/systemloader/systemv
src/sbt-test/rpm/override-start-script-systemv/test
src/sbt-test/rpm/override-start-script-upstart/build.sbt
src/sbt-test/rpm/override-start-script-upstart/project/plugins.sbt
src/sbt-test/rpm/override-start-script-upstart/src/templates/start
src/sbt-test/rpm/override-start-script-upstart/src/templates/systemloader/upstart
src/sbt-test/rpm/override-start-script-upstart/test

I added some tests for checking the override behavior of upstart, systemd, and systemv start scripts for rpm packaging (will circle back around to debian when I have time). It seems that the start script template can only be overridden for the [UpstartPlugin](https://github.com/sbt/sbt-native-packager/blob/e4e6504c1f6a75fb346958f68d0f7c13fec26877/src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/UpstartPlugin.scala) and [SystemdPlugin](https://github.com/sbt/sbt-native-packager/blob/e4e6504c1f6a75fb346958f68d0f7c13fec26877/src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemdPlugin.scala). However, the [SystemVPlugin](https://github.com/sbt/sbt-native-packager/blob/e4e6504c1f6a75fb346958f68d0f7c13fec26877/src/main/scala/com/typesafe/sbt/packager/archetypes …

Adding rpm override script tests

---

src/main/resources/com/typesafe/sbt/packager/archetypes/ash-template

`[ "foo" == "bar" ]` is not valid posix. It should be a single =, or else you'll get "unexpected operator/operand" on a posix compliant shell:
> posh
$ [ "foo" = "foo" ] && echo yes 
yes
$ [ "foo" == "foo" ] && echo yes
posh: [: ==: unexpected operator/operand
> dash                                                                                                               ⏎
$ [ "foo" = "foo" ] && echo yes 
yes
$ [ "foo" == "foo" ] && echo yes
dash: 2: [: foo: unexpected operator

fix a bug in the ash-template

---

src/main/scala/com/typesafe/sbt/packager/rpm/RpmMetadata.scala
src/sbt-test/rpm/scriptlets-rpm/build.sbt

The removal of the symlinks in `%preun` now is only triggered during an uninstall. Before an update of an package removed the symlinks and left the package in a non-functioning state.

[rpm] Fixes #894. Symlinks only removed during uninstall, not during update of RPM.

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

When the SBT project version follows semantic versioning, and includes build metadata (e.g. 1.0.0+abcdef1) the Docker tag and publish is broken. The most reasonable way to handle this is to modify the build.sbt to adjust the version in Docker scope.
Right now, the DockerAlias pulls the version from the project scope.
-- Modified build.sbt --
```
(version in Docker) := version.value.split('+')(0)
```
-- In SBT console --
```
[sample-server] $ show dockerAlias
[info] DockerAlias(Some(some.registry),None,aergo-server,Some(1.0.0+abcdef1))
[sample-server] $ show docker:version
[info] 1.0.0
```
-- In SBT console after fix --
```
[sample-server] $ show dockerAlias
[info] DockerAlias(Some(some.registry),None,aergo-server,Some(1.0.0))
[sample-server] $ show docker:version
[info] 1.0.0
```

DockerAlias should have version scoped to Docker

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/sbt-test/docker/simple-docker/build.sbt
src/sbt-test/docker/simple-docker/test
src/sbt-test/docker/simple-sudo-docker/build.sbt
src/sbt-test/docker/simple-sudo-docker/project/plugins.sbt
src/sbt-test/docker/simple-sudo-docker/src/main/scala/Main.scala
src/sbt-test/docker/simple-sudo-docker/test
src/sphinx/formats/docker.rst

Per discussion in https://github.com/sbt/sbt-native-packager/pull/903
When building docker images on CentOS, Fedora or RHEL, the permissions on /var/run/docker.socket have restricted access, preventing Docker build and push commands as a normal user from executing without severely compromising the system.
See http://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/
Therefore, I've added a new setting which supports replacing the default docker shell exec command so that I can instead use `sudo docker` (which is the recommended method for executing Docker on CentOS, Fedora and RHEL), or completely replace the `docker` command with a path to a shell script.
With this new setting and the regular `dockerBuildCommand` and …

Add dockerExecCommand setting

---

src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala

Remove unnecessary entries from the `linuxPackageMappings`

If mappings are empty don't add them to the linuxPackageMappings

---

src/sphinx/formats/rpm.rst

Added the correct scoping to the docs explaining the configWithNoReplace helper.

[rpm] Fix configWithNoReplace docs

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-forwarder-template

This will make the template more portable. The regular bash-template uses the `env` version
therefore the forwarder should use it too.
This fixes #921

Change shebang in bash-forwarder-template to `#!/usr/bin/env bash`.

---

appveyor.yml
build.sbt

- use chocolatey
- add extra ci command

Fix appveyor build

---

src/main/scala/com/typesafe/sbt/packager/debian/DebianMetadata.scala
src/main/scala/com/typesafe/sbt/packager/debian/DebianPlugin.scala
src/main/scala/com/typesafe/sbt/packager/debian/Keys.scala
src/main/scala/com/typesafe/sbt/packager/debian/NativePackaging.scala

The `DebianPlugin` now uses the `stage` task to generate a staged folder where the `dpkg` build process is executed.
- Deprecated `debianExplodePackage`
- Replaced deprecated symbolic operators
- Fixed IntelliJ warnings

Use stage  task instead of debianExplodedPackage

---

src/main/resources/com/typesafe/sbt/packager/rpm/brpJavaRepackJar
src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala
src/sbt-test/rpm/scriplets-no-javarepack-rpm/build.sbt
src/sbt-test/rpm/scriplets-no-javarepack-rpm/project/plugins.sbt
src/sbt-test/rpm/scriplets-no-javarepack-rpm/test
src/sbt-test/rpm/scriplets-use-javarepack-rpm/build.sbt
src/sbt-test/rpm/scriplets-use-javarepack-rpm/project/plugins.sbt
src/sbt-test/rpm/scriplets-use-javarepack-rpm/test
src/sbt-test/rpm/scriptlets-override-build-rpm/test
src/sbt-test/rpm/scriptlets-override-rpm/test
src/sbt-test/rpm/scriptlets-rpm/test
src/sbt-test/rpm/sysvinit-rpm/test
src/sphinx/formats/rpm.rst

Fixes #789 where the value of `rpmBrpJavaRepackJars` was required to be set to `false` in order for repacking *not* to occur.
I've done three things:
1. Created a shorter pre script which utilizes `sed` in a single liner, since there are versions which don't support multi line macros (when running the test I kept getting errors about macro having an empty body, see [this](https://www.redhat.com/archives/fedora-packaging/2005-July/msg00113.html) for more). I also changed the macro prefix from %define to %global, as that's the recommended approach by Fedora.
2. Negated the default flag from `false` to `true`. My assumption was people might not want to disable repackaging out of the box, but feel free to tell me otherwise
3. Added a test to validate that the removal of brpRepack works when …

Fixes issue #789 where brpJavaRepack was negated

---

src/sphinx/formats/docker.rst

Given how these are set by default: https://github.com/sbt/sbt-native-packager/blob/v1.2.0-M8/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L78-L82
and how they are tested: https://github.com/sbt/sbt-native-packager/blob/v1.2.0-M8/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L78-L82
I'm pretty sure the "in Docker" is wrong (i.e. won't have any effect).

Drop "in Docker" in some docker keys

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/AshScriptPlugin.scala
src/sbt-test/ash/memory-settings/build.sbt
src/sbt-test/ash/memory-settings/project/plugins.sbt
src/sbt-test/ash/memory-settings/src/main/scala/MainApp.scala
src/sbt-test/ash/memory-settings/test

Added tests to the initial code from #942 and fixed a bug in the `bashScriptDefines`.
Previously, there was no addJava function defined in the ash-template.
This resulted in warnings when the ash script ran because template
declares expects the function to be defined.
Now, the addJava function is defined. It adds options to java_opts. As a
convenience, if JAVA_OPTS is set then it is added to java_opts. This
makes the ash script behave more like the bash script. The result is
then passed to java at the end of the script.

Define addJava in ash-template

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template

Replaced occasional tabs with spaces — this allow the script (and its output) to have the same look without depending on tab size = 8. Probably mixing spaces and tabs in single line is not what original author of these lines wanted.

Some trivial formatting fix (tabs -> spaces)

---

src/main/scala/com/typesafe/sbt/packager/windows/WixHelper.scala

Fixes handling of directories with numbers.

---

src/main/scala/com/typesafe/sbt/packager/debian/DebianPlugin.scala

Fixes #587
By calling `SettingsHelper.makeDeploymentSettings` twice DebianDeployPlugin only adds "changes" file, but not the "deb" file to the list of artifacts.

Fix DebianDeployPlugin not publishing deb file

---

src/main/resources/com/typesafe/sbt/packager/archetypes/etc-default-systemd-template
src/main/resources/com/typesafe/sbt/packager/archetypes/etc-default-template

It took me a while to find out how to configure my service startup.
I propose to
* Add extra space so that variables meant as documentation don't get replaced
* Add links into documentation

Improve comments in etc-default files

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/sbt-test/docker/rmi/build.sbt
src/sbt-test/docker/rmi/project/plugins.sbt
src/sbt-test/docker/rmi/src/main/scala/Main.scala
src/sbt-test/docker/rmi/test
src/sphinx/formats/docker.rst

This task will call `docker rmi` by default.
The command can be controlled using the dockerRmiCommand key.
Fixes #501 
- Added a test that tests for the images' existence before and after
- Reused `clean` as it is familiar
- Command override provided as key
- Documentation

Add docker:clean task

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/override-commands/build.sbt
src/sphinx/formats/docker.rst

Replace deprecated java Docker container with openjdk (#877)

---

src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-debian-template
src/sbt-test/debian/sysvinit-deb/build.sbt

The removal of the quotes should fix this if no `stdout_redirect` is set. Also the file had mixed indenting of 2 and 4 spaces, therefore I adjusted it to 2 spaces.
This should fix #955 . Travis is green on our fork: https://travis-ci.org/wegtam/sbt-native-packager/branches .

Prevent empty double quotes in start daemon line.

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/sphinx/formats/docker.rst

Currently, there is no way to set the organizaiton or user for a docker
image. The documented practice is to misuse the dockerRepository setting
to set the username or organization. However, there is already
functionality in place for the DockerAlias class to support a separate
username.
This commit adds a dockerUsername setting which ties into the existing
DockerAlias username functionality.

Add Setting for Docker User

---

src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-debian-template

Adjust mixed indenting in start-debian-template.

---

src/main/scala/com/typesafe/sbt/packager/debian/JDebPackaging.scala
src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

Issue 972 pretty print docker alias

---

src/main/scala/com/typesafe/sbt/packager/debian/JDebPackaging.scala

Fixes issues with sbt-coursier and the jdeb maven plugin.

Add maven-plugin to classpathTypes when using JDebPlugin

---

src/sphinx/formats/docker.rst

Requiring docker 1.10 or higher.

FIX #981 Documentation incorrect -- Docker v1.10 or higher required

---

src/main/scala/com/typesafe/sbt/packager/rpm/RpmHelper.scala
src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala
src/sbt-test/rpm/simple-rpm/build.sbt
src/sbt-test/rpm/simple-rpm/test

Similar to `debian:stage`, `docker:stage` and `universal:stage` the rpm workspace can now be stage as well.
This should fix #848

Implement stage command for rpm

---

src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala
src/sbt-test/rpm/snapshot-rpm/build.sbt
src/sbt-test/rpm/snapshot-rpm/project/plugins.sbt
src/sbt-test/rpm/snapshot-rpm/src/universal/conf/test
src/sbt-test/rpm/snapshot-rpm/test

Fixes #971 - feedback appreciated!

Use SNAPSHOT for release when snapshot version

---

src/main/scala/com/typesafe/sbt/packager/SettingsHelper.scala

Hi there
This PR introduce the ability to provide an artifact classifier for default packages when calling `makeDeploymentSettings`. 
We need this feature in our build process and I see no other workaround that to produce second artifacts with `addPackage` call.

Allow specifying classifier for default package in deployment settings

---

src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemloaderPlugin.scala

I got the following error when upgrading:
```
/var/tmp/rpm-tmp.zpTtMD: line 4: restartService: command not found
```

Fix a bug which cause upgrade failing because of no restartService

---

src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala
src/sbt-test/rpm/snapshot-override-rpm/build.sbt
src/sbt-test/rpm/snapshot-override-rpm/project/plugins.sbt
src/sbt-test/rpm/snapshot-override-rpm/src/universal/conf/test
src/sbt-test/rpm/snapshot-override-rpm/test

strip snapshot suffix safely (#1004)

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/sbt-test/docker/labels/build.sbt
src/sbt-test/docker/labels/test

For now, `dockerLabels` doesn't generate labels with wrapping `"` character.
- build.sbt
```sbt
dockerLabels := Map("foo" -> "bar")
```
- Generated Dockerfile
```Dockerfile
LABEL foo=bar
```
This may have issue with string values with spaces
- build.sbt
```sbt
dockerLabels := Map("fooBar" -> "foo bar")
```
- Generated Dockerfile
```Dockerfile
LABEL fooBar=foo bar
```
Fixed that to wrap with `"` character.
- build.sbt
```sbt
dockerLabels := Map("fooBar" -> "foo bar", "number" -> 123)
```
- Generated Dockerfile
```Dockerfile
LABEL fooBar="foo bar"
LABEL number=123
```
Also, `dockerLabels` will accept map containing any type of value and make them string automatically(for convenience).
Only `Number` typed values won't be wrapped with `"` character
- [Docker doc …

Wrap docker labels with " character

---

src/sphinx/archetypes/systemloaders.rst

Copied correct override path from `archetypes/cheatsheet.rst`. Also fixed markup - Sphinx nested lists must be separated by blank line.

Fix inconsistency in docs

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala

Adds a note at the end of the bash usage message with the available main classes that can be used with the runner.
Example generated usage:
```
...
In the case of duplicated or conflicting options, basically the order above
shows precedence: JAVA_OPTS lowest, command line options highest except "--".
Available main classes:
com.foo.Main
com.bar.Main
```

add available main classes to the usage notes in bash script

---

src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala
src/main/scala/com/typesafe/sbt/packager/jar/LauncherJarPlugin.scala
src/sbt-test/jar/launcher-jar with spaces/build.sbt
src/sbt-test/jar/launcher-jar/build.sbt

If you run the batch script from `C:\Program Files\my-app\bin\my-app.bat` you'll get an error like this:
> Error: Unable to access jarfile C:\Program
#581 fixed the path being quoted in the bash script, but it still wasn't quoted in the bat script.
Before:
```bat
set "APP_MAIN_CLASS=-jar %APP_LIB_DIR%\app-1.0-SNAPSHOT-launcher.jar"
```
After:
```bat
set "APP_MAIN_CLASS=-jar "%APP_LIB_DIR%\app-1.0-SNAPSHOT-launcher.jar""
```
Fixes #913

Fix launcher jar paths not being quoted on Windows

---

build.sbt
project/build.properties
src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/override-commands/build.sbt
src/sbt-test/docker/override-commands/test
src/sbt-test/docker/rmi/test
src/sphinx/formats/docker.rst

Update Spotify docker-client
Update sbt
Update documentation
Update tests
I ran all the tests except for the `sudo` one since I don't have `sudo` set up.
Closes #1033

Use LABEL instead of MAINTAINER for maintainers

---

src/main/scala/com/typesafe/sbt/packager/rpm/RpmHelper.scala
src/main/scala/com/typesafe/sbt/packager/rpm/RpmMetadata.scala
src/sbt-test/rpm/scriptlets-rpm/build.sbt
src/sbt-test/rpm/simple-rpm/build.sbt
src/sbt-test/rpm/symlink-rpm/build.sbt
src/sbt-test/rpm/symlink-rpm/project/plugins.sbt
src/sbt-test/rpm/symlink-rpm/test

I'm trying to bring back to life a very old PR: https://github.com/sbt/sbt-native-packager/pull/916
Here I'm adding back the original test made by @dpennell and I'm reapplying his changes on top of the current master branch.
An interesting improvement is that by describing symbolic links as part of RPM's spec file, it can remove them during uninstall, leaving no empty folders behind. Previously, the links were removed in the `postun` hook, after RPM tried to rid of its managed folders, resulting in empty directories whenever there was a symbolic link inside them.
I've tested this with a project I'm working on using a CentOS VM.

Refresh PR: Treat symlinks as normal files in spec file

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bat-template
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/ApplicationIniGenerator.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BatStartScriptKeys.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BatStartScriptPlugin.scala
src/sbt-test/windows/app-home-var-expansion/build.sbt
src/sbt-test/windows/app-home-var-expansion/project/plugins.sbt
src/sbt-test/windows/app-home-var-expansion/src/main/scala/MainApp.scala
src/sbt-test/windows/app-home-var-expansion/test
src/sbt-test/windows/dynamic-app-env-name/build.sbt
src/sbt-test/windows/dynamic-app-env-name/project/plugins.sbt
src/sbt-test/windows/dynamic-app-env-name/src/main/scala/MainApp.scala
src/sbt-test/windows/dynamic-app-env-name/test
src/sbt-test/windows/memory-settings/build.sbt
src/sbt-test/windows/memory-settings/project/plugins.sbt
src/sbt-test/windows/memory-settings/src/main/scala/MainApp.scala
src/sbt-test/windows/memory-settings/test
src/sphinx/archetypes/java_app/customize.rst

I added some functions to the batch script to mirror the bash script. This means you can set extra java args using similar syntax:
```sbt
batScriptExtraDefines += """call :add_java "-Dconfig.file=%APP_HOME%\conf\production.conf""""
bashScriptExtraDefines += """addJava "-Dconfig.file=${app_home}/../conf/production.conf""""
```
Previously the batch script used a dynamic environment variable name `<APP_NAME>_HOME`, which is difficult to use from the sbt build. Now it's called `APP_HOME` always.
The bat script will still read `<APP_NAME>_HOME` from the environment for backwards compatibility.
The bat script now supports `javaOptions in Universal` via a generated `application.ini` file. Fixes #688
The ini file uses the `-J` syntax, so you can use the same ini file for both bat and bash, or you …

Windows batch script improvements

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerSpotifyClientPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala

I get errors when starting sbt when the machine can't connect to docker
```
An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/version: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.
```
Since fetching the docker version involves starting a process and/or making an HTTP request, it seems like it should be a task rather than a setting.

Convert dockerVersion from a setting to a task

---

src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/ApplicationIniGenerator.scala

Now that the BAT plugin supports application.ini, when you use both plugins together you get duplicate mappings:
```
[info] * (target/universal/tmp/conf/application.ini,conf/application.ini)
[info] * (target/universal/tmp/conf/application.ini,conf/application.ini)
```
This isn't necessarily a problem, but unzipping the universal dist will try to create the file twice:
```
$ unzip app-1.0-SNAPSHOT.zip
Archive:  app-1.0-SNAPSHOT.zip
inflating: app-1.0-SNAPSHOT/conf/application.ini
replace app-1.0-SNAPSHOT/conf/application.ini? [y]es, [n]o, [A]ll, [N]one, [r]ename:
```
This change filters out the duplicate mapping. Alternatively maybe it would be better to have an `ApplicationIniPlugin` which is a dependency of both the `BatStartScriptPlugin` and `BashStartScriptPlugin`

Fix duplicate application.ini mappings when both BASH and BAT plugins are used

---

src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/StartScriptMainClassConfig.scala
src/test/scala/com/typesafe/sbt/packager/StartScriptMainClassConfigSpec.scala

Fixes an issue where the main class is not discovered because it's located in a different jar on the classpath. For example:
```sbt
> show mainClass
[info] Some(play.core.server.ProdServerStart)
> show discoveredMainClasses
[info] * com.acme.CustomMainClass
```
This matches the first case, and consequently the discovered main class is ignored
```
case Some(main) if discoveredMainClasses.size == 1 => SingleMain(main)
```

Improve main class detection

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/entrypoint/test
src/sbt-test/docker/labels/build.sbt
src/sbt-test/docker/ports/test
src/sbt-test/docker/test-executableScriptName/build.sbt
src/sbt-test/docker/test-packageName-universal/build.sbt
src/sbt-test/docker/test-packageName/build.sbt
src/sbt-test/docker/udp-only-ports/test
src/sbt-test/docker/volumes/test

Remove redundant Dockerfile

---

src/main/scala/com/typesafe/sbt/packager/debian/JDebPackaging.scala

Don't compress packages using the JDeb debian packager

---

_sources/recipes/custom.rst.txt

The `packageArchetype.java_server` syntax is deprecated and broken.
Probably the [example](https://github.com/muuki88/sbt-native-packager-examples/tree/master/multi-module-build) should also be updated.

Update documentation for multi-module builds

---

src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala
src/main/scala/com/typesafe/sbt/packager/universal/UniversalPlugin.scala
src/sbt-test/universal/test-zips/build.sbt
src/sbt-test/universal/test-zips/test
test-project-simple/build.sbt

fix packageZipTarball defaults for UniversalDocs and UniversalSource

---

src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BatStartScriptPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/CommonStartScriptGenerator.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/ScriptUtils.scala
src/sphinx/archetypes/java_app/index.rst
src/test/scala/com/typesafe/sbt/packager/archetypes/scripts/ScriptUtilsTest.scala

This PR tries to lower the chance of generation of multiple scripts
with equal names in one archive. Fixes #1016.
Additionally, an attempt was made to improve the word splitting
for the script names, so, for example `UITest` becomes `ui-test`
and not `u-i-test`.
I had to edit `ForwarderScripts.apply(...)` as well but I'm not sure I did it the right way.

Change startup script name generation

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

When originally introduced in 885541e8a603273423100c0694e09804ebe654d0 `dockerTarget` used `dockerRepository` and `dockerUsername` defined in the `Docker` scope.
Sometime in the process of `dockerTarget` being refactored and renamed to `dockerTag` and then `dockerAlias`, it was made to use the value from `dockerRepository` from the global scope instead of the docker scope. ie, defining 
```
dockerRepository in Docker := "my-custom-repository"
dockerUsername in Docker := "john"
```
used to work, but now has no effect, as shown by looking up the value of dockerAlias:
```
sbt:test-docker> docker:dockerAlias
[info] DockerAlias(None,None,test-docker,Some(0.0.0-SNAPSHOT))
```
Instead one must define them globally
```
dockerRepository := "my-custom-repository"
dockerUsername := "john"
```
``` …
```

DockerAlias should use dockerRepository and dockerUsername from Docker scope

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/test-executableScriptName/build.sbt
src/sbt-test/docker/test-packageName-universal/build.sbt
src/sbt-test/docker/test-packageName/build.sbt

We sometimes need to change the the WORKDIR, and when we do the ENTRYPOINT becomes invalid.
In general it's good to use absolute paths unless things are sementicaly tied to each other, which is not the case of ENTRYPOINT regarding WORKDIR

Give an absolute path to the entrypoint

---

src/sphinx/formats/debian.rst

Added some documentation that recommends usage of JRE dependencies in Debian packages, and explains how to configure them properly.
Follows up discussion in https://github.com/sbt/sbt-native-packager/issues/1106.

JRE dependencies in Debian documentation

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerVersion.scala

Add support for numbers in the release version. This allows version
detection to parse server version of the form '18.03.0-ce-rc3'.

Fix docker server version parsing

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template
src/sbt-test/docker/jdk-versions/build.sbt
src/sbt-test/docker/jdk-versions/jdk10/src/main/scala/Hello.scala
src/sbt-test/docker/jdk-versions/jdk8/src/main/scala/Hello.scala
src/sbt-test/docker/jdk-versions/jdk9/src/main/scala/Hello.scala
src/sbt-test/docker/jdk-versions/project/plugins.sbt
src/sbt-test/docker/jdk-versions/test

The current Java version check in 'bash-template' relies on a string comparison for numbers.
As far as I could investigate this check fails at least for bash 4.3.48 on a xenial/sid based docker images.
It fails for the latest JDK release 10, as "10" is not greater than "1.6" when compared as string in bash.
Later bash version seem to treat this check differently.
I changed the version check to compare numbers. For versions 1.x.y, the check extracts the minor version "x" and compares agains "6". If the major version is unequal to "1", the major version is compared against "6".
Using docker openjdk images I added scripted test.
Tested with bash 4.3.48 and 4.4.19, docker 17.12.0-ce.

fixed Java version check in bash template

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template

`-XX...` arguments now added to the JVM. Without this, the following fails:
```sbt
javaOptions in Universal ++= Seq(
"-XX:+UnlockExperimentalVMOptions",
"-XX:+UseCGroupMemoryLimitForHeap"
)
```
```bash
Bad root server path: /opt/docker/-XX:+UnlockExperimentalVMOptions
```

Process -XX arguments as JVM args

---

.travis.yml
src/main/scala-sbt-0.13/com/typesafe/sbt/packager/SettingsHelper.scala
src/main/scala-sbt-1.0/com/typesafe/sbt/packager/SettingsHelper.scala
src/sbt-test/universal/publish/build.sbt
src/sbt-test/universal/publish/test

It's a small change including a publishM2 action. Currently the sbt-native-packages only supports`publish` and `publishLocal` actions. 
- **O.S.:** MacOSX, Darwin <host> 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
- **bash:** GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
- **sbt:** 1.1.1
- **scala:** Scala code runner version 2.12.5 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc
- **java jdk:** java version "1.8.0_162",Java(TM) SE Runtime Environment (build 1.8.0_162-b12), Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

Included feature publishM2

---

src/sphinx/archetypes/index.rst
src/sphinx/index.rst
src/sphinx/introduction.rst

Some more grammar and typos that I could correct while going through the docs

More grammar changes in docs

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/main/scala/com/typesafe/sbt/packager/docker/dockerfile.scala
src/sbt-test/docker/envVars/build.sbt
src/sbt-test/docker/envVars/project/plugins.sbt
src/sbt-test/docker/envVars/test
src/sphinx/formats/docker.rst

added docker environment variables support

[Docker] add dockerEnvVars support

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/override-commands/build.sbt
src/sphinx/formats/docker.rst

Because the latest version of openjdk has moved to Java 10, which is not fully compatible with Scala.
This resolves https://github.com/sbt/sbt-native-packager/issues/1146

Change openjdk:latest to openjdk:8.

---

src/main/scala/com/typesafe/sbt/packager/debian/DebianPlugin.scala
src/sbt-test/debian/daemon-group-gid-deb/build.sbt
src/sbt-test/debian/daemon-user-deb/build.sbt
src/sbt-test/debian/daemon-user-uid-deb/build.sbt

Fix generated chown command (#1151)

---

src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemd/start-template
src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemdPlugin.scala

We noticed the `killTimeout` `SettingKey` wasn't being used by the SystemD template. We've added it in similarly to how `SuccessExitStatus` was added
Co-authored-by: Andrew Smitherim <andrew.smitherim@gmail.com>

Add kill timeout to SystemD service as TimeoutStopSec

---

build.sbt
src/main/scala/com/typesafe/sbt/packager/debian/JDebPackaging.scala

This should fix #1097 and reduce some of the dependency issues in builds that don't require debian packaging.

FIX #1097 Put jdeb back in provided scope

---

src/sphinx/formats/graalvm-native-image.rst
src/sphinx/formats/index.rst

1. I was unable to see the documentation in the table of contents
2. GraalVM native-image plugin should be in the diagram
3. Added quickstart steps for GraalVM by reusing our Travis installer.
May need to update the URL inside of it depending on whether there're changes in #1166 - best merged only after.

Improve the GraalVM native-image documentation

---

src/sphinx/formats/graalvm-native-image.rst

So that we needn't update this document if there are any changes in the script.

GraalVM docs to use the installer from master branch

---

src/main/scala-sbt-1.0/com/typesafe/sbt/packager/MappingsHelper.scala

This PR updates the scaladoc for `contentOf` method to use the same signature as the code.

Update scaladoc in contentOf to match method signature

---

src/main/scala/com/typesafe/sbt/packager/windows/Keys.scala
src/main/scala/com/typesafe/sbt/packager/windows/WindowsPlugin.scala
src/sbt-test/windows/custom-wix/build.sbt
src/sbt-test/windows/custom-wix/project/plugins.sbt
src/sbt-test/windows/custom-wix/src/wix/main.wsx
src/sbt-test/windows/custom-wix/src/wix/ui.wsx
src/sbt-test/windows/custom-wix/test
src/sphinx/formats/windows.rst

Closes #1176 
Solved this, as described in the original issue, by providing a `wixFiles` task. All the mentioned files are copied to `target/windows` in a flat structure. A more idiomatic solution would probably be to somehow add `managedSourceDirectories`/`unmanagedSourceDirectories`  mechanics to the `Windows` configuration - however, I have neither time nor energy to dig deeper into this at the moment.

WindowsPlugin: support multiple wxs sources (#1176)

---

build.sbt
project/plugins.sbt

Fix #1185 Add MiMa to check binary compatibility

---

src/sphinx/formats/docker.rst

Update Docker plugin docs

---

build.sbt
src/main/scala/com/typesafe/sbt/packager/docker/DockerSpotifyClientPlugin.scala

Attempt to fix #1194 by trying to copy the method used in #1097.

Attempt to move docker-client dependency back to the provided scope

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/file-permission/build.sbt
src/sbt-test/docker/file-permission/change.sbt
src/sbt-test/docker/file-permission/changes/strategy-copychown.sbt
src/sbt-test/docker/file-permission/changes/strategy-none.sbt
src/sbt-test/docker/file-permission/changes/write-execute.sbt

Fixes #1195
Since the user of the fabric8 image is already non-root, stage0 fails with
```
chmod: changing permissions of '/opt/docker': Operation not permitted
```
This switches the stage0 user to root explicitly so we can run `chmod` in there. In the actual image the user is set back to 1001.

Run stage0 as root during Docker build

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/file-permission/build.sbt
src/sbt-test/docker/file-permission/changes/strategy-copychown.sbt
src/sbt-test/docker/volumes/test
src/sphinx/formats/docker.rst

Fixes #1198
Numeric USER directive is now controlled using `daemonUserUid in Docker`, which defaults to `Some("1001")`.
To get back to previous behavior the following can be used:
```scala
daemonUserUid in Docker := None
daemonUser in Docker    := "daemon"
```

Use daemonUserUid to opt-out of numeric USER

---

src/sphinx/recipes/custom.rst

Now it works with sbt-proguard 0.3.0.
`proguardOptions` were taken from [their example](https://github.com/sbt/sbt-proguard/blob/v0.3.0/src/sbt-test/proguard/simple/build.sbt).
#518 #721

Update Proguard example

---

src/main/scala/com/typesafe/sbt/packager/rpm/RpmHelper.scala

Currently stdout for building an RPM gets output at error level. 
```
[error] + umask 022
[error] + cd /home/david/test/target/rpm/BUILD
[error] + /bin/rm -rf /home/david/test/target/rpm/buildroot
[error] + exit 0
```

Don't write RPM standard output as error

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/file-permission/build.sbt
src/sbt-test/docker/file-permission/changes/strategy-none-gid.sbt
src/sbt-test/docker/file-permission/test

This is to demonstrate that #1218 is indeed a bug.
The fix will be provided in a subsequent commit.

Bug #1218: docker:publishLocal fails because of non-existent gid

---

.travis.yml
README.md
build.sbt
src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template
src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bat-template
src/main/scala/com/typesafe/sbt/packager/Keys.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppKeys.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppKeys2.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppPackaging.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkKeys.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/AshScriptPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BatStartScriptPlugin.scala
src/sbt-test/jlink/test-jlink-minimal/build.sbt
src/sbt-test/jlink/test-jlink-minimal/project/plugins.sbt
src/sbt-test/jlink/test-jlink-minimal/src/main/java/JlinkTestApp.java
src/sbt-test/jlink/test-jlink-minimal/test
src/sphinx/archetypes/misc_archetypes.rst

This scans the `fullClasspath` (using `jdeps`), and builds a JVM image (using `jlink`) from all the referenced modules. The image is then "mounted" to a configurable prefix in `Universal / mappings` (`jre/` by default). The image location is then passed to the start scripts with the highest priority (higher than `JAVA_HOME`).
Potential issues (feedback required):
- I'm not sure how to wire this into the existing CI setup, since the whole thing requires Java 11.
- Java 9 support is theoretically possible, but would require some fiddling with `jdeps` output. I'm not sure it is worth the trouble.
- It might be better to only limit the image to the standard modules (`java.*`, `javafx.*`, `jdk.*`), since everything else is already provided by the `JavaAppPackaging`. I can think both of pros …

Add a simple jlink wrapper

---

src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerAntHelper.scala

- grammar: 'find' -> 'found'
- settings key requires `Option[File]` not `Option[String]`

fix error message for jdkpackager when antTaskLib is missing

---

README.md

Docker-containers 1.2.12 isn't valid for the current version of sbt-native-packager -- it looks for docker alias, which doesn't exist:
```
[error] java.lang.NoSuchMethodError: com.typesafe.sbt.packager.docker.DockerAlias.versioned()Ljava/lang/String;
[error] 	at com.dwolla.sbt.docker.DockerContainerPlugin$.$anonfun$tasks$1(DockerContainerPlugin.scala:36)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at …
```

remove docker-containers

---

README.md

[sbt-typesafe-conductr](https://github.com/sbt/sbt-conductr) is EOL

sbt-conductr is EOL

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/DockerVersion.scala
src/test/scala/com/typesafe/sbt/packager/docker/DockerVersionSpec.scala

Improve Docker version detection

---

.travis.yml
src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkKeys.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala
src/sbt-test/jlink/test-jlink-missing-deps/bar/src/main/java/bar/Bar.java
src/sbt-test/jlink/test-jlink-missing-deps/build.sbt
src/sbt-test/jlink/test-jlink-missing-deps/foo/src/main/java/foo/Foo.java
src/sbt-test/jlink/test-jlink-missing-deps/project/plugins.sbt
src/sbt-test/jlink/test-jlink-missing-deps/test
src/sbt-test/jlink/test-jlink-missing-deps/withIgnore/src/main/java/WithIgnore.java
src/sbt-test/jlink/test-jlink-missing-deps/withoutIgnore/src/main/java/WithoutIgnore.java
src/sphinx/archetypes/misc_archetypes.rst

As outlined [here](https://github.com/sbt/sbt-native-packager/pull/1225#issuecomment-492264246):
1. Since `jdeps --print-module-deps` is unreliable - switch to parsing the full `jdeps`output.
1. The new `jdeps` behavior (throwing an error for missing dependencies) seems to be useful - include similar functionality into the new implementation.
1. Add a fine-grained way to silence missing dependencies from the previous point (`jlinkIgnoreMissingDependency`). Add convenience helpers (`JlinkPlugin.Ignore`).
1. Add a test for the new functionality.
1. Test the plugin against JDK 12.
General improvements:
1. Add a task for the list of modules (`jlinkModules`) to allow manually adding/removing these.
1. Add a level of indirection when using `Compile / fullClasspath` to allow injecting classpath …

Fix dependency handling in JlinkPlugin (+ general improvements)

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/file-permission/build.sbt
src/sbt-test/docker/test-busybox-create-user/build.sbt
src/sbt-test/docker/test-busybox-create-user/project/plugins.sbt
src/sbt-test/docker/test-busybox-create-user/src/main/scala/Main.scala
src/sbt-test/docker/test-busybox-create-user/test

This should allow more flexibility when using images based on traditional `useradd/groupadd` and also Busybox-based systems using `adduser/addgroup`. This should provide an improvement for #1202

Possible improvement for #1202

---

src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkKeys.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala
src/sphinx/archetypes/misc_archetypes.rst
src/test/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkSpec.scala

Closes #1240
Everything is as outlined in #1240, except I've decided against globbing in p.1. The semantics for that would have to be different enough to be confusing. Instead I've added simple package prefix matching.

Assorted JlinkPlugin improvements

---

src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala
src/sbt-test/jlink/test-jlink-misc/build.sbt
src/sbt-test/jlink/test-jlink-misc/project/plugins.sbt
src/sbt-test/jlink/test-jlink-misc/test
src/test/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkSpec.scala

Closes #1243 .
1. Changed the plugin to parse JDK's `release` file and get the value of `JAVA_VERSION` property. The "useful" part of the version number (e.g. 11 for 11.0.3, or 9 for 1.9.0), is then passed to jdeps (`--multi-release`).
1. Added a `scripted` test project for this. There's a bit of over-engineering here, so that in the future we don't have to add a whole test project for simple chages like this.
1. Changed the way we run Java tools, so that in case of an error the output is dumped to the SBT log.

JlinkPlugin: support multi-release dependencies

---

src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala

This makes it easier to build the ignore expression afterwards.

JlinkPlugin: Sort missing dependencies before logging

---

src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala
src/sbt-test/jlink/test-jlink-misc/build.sbt
src/sbt-test/jlink/test-jlink-misc/test
src/sphinx/archetypes/misc_archetypes.rst

Closes #1247 .
This is a short-term solution to #1247, as outlined in https://github.com/sbt/sbt-native-packager/issues/1247#issuecomment-510532079 (point 1). The long-term solution (`JlinkPlugin` refactoring/rewrite - https://github.com/sbt/sbt-native-packager/issues/1247#issuecomment-510472779) will be a separate issue.
1. Fix `jlink` `--module-path` separator issue.
1. Filter detected dependencies - only link the platform modules.
1. Change `jlinkModulePath` to default to an empty list - we don't need it for platform modules.
Detecting platform modules has special cases - for [historical reasons](https://github.com/eclipse-ee4j/ee4j/issues/34) some Jakarta modules use `java.*` names, so we have to exclude them on a case by case basis. I'm not positive I got all of these - some seem to …

JlinkPlugin: restrict linking to platform modules

---

project/build.properties
src/main/scala/com/typesafe/sbt/packager/rpm/RpmHelper.scala

Fox #1246 flaky rpm tests

---

build.sbt
src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
src/sbt-test/ash/command-line-settings/build.sbt
src/sbt-test/ash/command-line-settings/project/plugins.sbt
src/sbt-test/ash/command-line-settings/src/main/scala/MainApp.scala
src/sbt-test/ash/command-line-settings/test

Added support for passing -Dconfig.resource and other JAVA_OPTS in default ash-template. See https://github.com/sbt/sbt-native-packager/issues/1254

Added command line JAVA_OPTS support for AshScriptPlugin

---

build.sbt
src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala
src/sbt-test/jlink/test-jlink-misc/build.sbt
src/sbt-test/jlink/test-jlink-misc/test

Closes #1266.
As described [here](https://github.com/sbt/sbt-native-packager/issues/1266#issuecomment-541610521), this uses a [launcher](https://github.com/eldis/java-tool-launcher) with `@argfile` support to pass large argument lists to `jdeps` (and `jlink`, just in case).
Since this approach only uses the `java` executable, I've changed the process handling to use SBT's `ForkRun`. This way we don't need to reimplement `javaOptions` and `javaHome` support. There are more hoops to jump through to get the process output out of it, but I think this is worth it.

JlinkPlugin: add support for huge classpaths

---

build.sbt
src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/main/scala/com/typesafe/sbt/packager/docker/dockerfile.scala
src/sbt-test/docker/autoremove-multi-stage-intermediate-images/build.sbt
src/sbt-test/docker/autoremove-multi-stage-intermediate-images/project/plugins.sbt
src/sbt-test/docker/autoremove-multi-stage-intermediate-images/src/main/scala/Main.scala
src/sbt-test/docker/autoremove-multi-stage-intermediate-images/test
src/sbt-test/docker/file-permission/build.sbt
src/sphinx/formats/docker.rst

Fixes #1229
Splitted in ~~three~~ four clean commits.
Let me know what you think. Thanks!
EDIT: Solution was inspired from here: https://github.com/moby/moby/issues/34513#issuecomment-389467566

Autoremove multi-stage intermediate image(s)

---

build.sbt
src/sbt-test/jlink/test-jlink-misc/build.sbt
src/sbt-test/jlink/test-jlink-misc/test

Fix 1.5.0 regression in JLinkPLugin error handling

---

src/sphinx/recipes/package_configuration.rst

It took me awhile to figure out how to run the scalac optimizer for only a production build. I used the BuildEnvPlugin described here and thought readers might benefit from the docs linking to a working example.

Add link to working example of BuildEnvPlugin

---

src/main/scala/com/typesafe/sbt/packager/universal/ZipHelper.scala

This was the root cause of #1035. It no longer is as big a problem since #1026 pre-validates that files exists, but it seems worth cleaning this up.

Improve error handling in ZIP utilities

---

.gitignore

I don't know if it is intended but I saw that the `.metals` folder was included in the last commits.
So I added entries to the `.gitignore` file.
Feel free to ignore this PR if this is intended.

Add folders from Bloop and Metals to gitignore

---

src/main/scala/com/typesafe/sbt/packager/rpm/RpmHelper.scala
src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala
src/sbt-test/rpm/test-artifactPath/build.sbt
src/sbt-test/rpm/test-artifactPath/project/plugins.sbt
src/sbt-test/rpm/test-artifactPath/test
src/sphinx/formats/rpm.rst

Introduce RPM / packageBin / artifactPath setting.

---

.github/workflows/validate-pr.yml
README.md
build.sbt
src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-forwarder-template
src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerAntHelper.scala
src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerKeys.scala
src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala
src/main/scala/com/typesafe/sbt/packager/universal/Keys.scala
src/main/scala/com/typesafe/sbt/packager/universal/ZipHelper.scala
src/sphinx/archetypes/java_server/index.rst
src/sphinx/formats/graalvm-native-image.rst
src/sphinx/formats/jdkpackager.rst
src/sphinx/formats/universal.rst

Change all references to macOS (MacOS X, MacOSX, OS X, OSX, macOSx, macosx, osx).
That leaves the `TRAVIS_OS_NAME` env var, which seems to only supports
the variant 'osx', as far as I can tell.
It also leaves the `packageOsxDmg`/`package-osx-dmg` task key, that is
both public binary API and public semantic API, as keys are global in
sbt's build state - so I just left it as is for now.

Change all references to macOS

---

README.md

A plugin that uses the DockerPlugin of sbt-native-packager to aid in creating kubernetes manifests

please add sbt-kubeyml

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
src/sbt-test/ash/command-line-settings/build.sbt
src/sbt-test/ash/command-line-settings/src/main/scala/MainApp.scala
src/sbt-test/ash/command-line-settings/test

This fixes #1302, and, in a much simpler way than #1276, #1264. Unfortunately, I don't understand the tests well enough to figure out where to hang a test for the bashisms specifically, nor the `addResidual` change. If you can give me some tips, I'd be glad to write them if you want me to.

Fix ash template

---

build.sbt
src/main/scala/com/typesafe/sbt/packager/graalvmnativeimage/GraalVMNativeImageKeys.scala
src/main/scala/com/typesafe/sbt/packager/graalvmnativeimage/GraalVMNativeImagePlugin.scala
src/sphinx/formats/graalvm-native-image.rst

* The final native-image executable cannot be located in the file
native-image.cmd unless the full path to native-image.cmd is
given. Therefore, a new parameter is provided to the user to
specify the native-image.cmd location.
* Picks the right CLASSPATH separator according to the OS
instead of hardcoded to colon. Using Colon will fail in Windows
build.
* Tested against GraalVM 20.0.0 and VS 2019.

Fix for native-image to work in Windows

---

src/sphinx/formats/graalvm-native-image.rst

There is a missing space between `` and word causes paragraph to overrun the right margin

Add space between inline-literal symbol and word

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/sbt-test/docker/test-layer-groups/build.sbt
src/sbt-test/docker/test-layer-groups/changes/nolayers.sbt
src/sbt-test/docker/test-layer-groups/layers.sbt
src/sbt-test/docker/test-layer-groups/test

The main purpose of this change is to make layer grouping more robust.  Instead of using a heuristic based on whether a library is in the same `organization` as the build (which is not always what you want, some builds may have sub projects with different organizations, and some builds may depend on external dependencies from the same organization), it checks whether the library in question is present in `projectDependencyArtifacts` (ie, whether its a dependency built by this build), if it is, then it goes in a higher layer.
Doing this change however required changing `dockerLayerGrouping` to be a `TaskKey` instead of a `SettingKey`, which is a non binary compatible change. So, `dockerLayerGrouping` has been deprecated, and a new `TaskKey`, `dockerGroupLayers` has been introduced.
Since a …

Improved layer grouping

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerSpotifyClientPlugin.scala

This adds support for pushing built tags in DockerSpotifyClientPlugin.
Additionally, this introduces a small refactoring to extract the
definition of the ProgressHandler, used by both building and pushing
tasks to log progress.

Add support for docker:publish in DockerSpotifyClientPlugin

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
src/sbt-test/ash/add-app-settings/build.sbt
src/sbt-test/ash/add-app-settings/project/plugins.sbt
src/sbt-test/ash/add-app-settings/src/main/scala/MainApp.scala
src/sbt-test/ash/add-app-settings/test

Closes https://github.com/sbt/sbt-native-packager/issues/862

Add addApp function to align with bash version

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

Normalize  paths when mapping generic files to docker

---

src/sphinx/formats/universal.rst

The sbt-native-packager docs use a lot of syntax that has been deprecated for years. Many of these will eventually end up in people's build files due to copy-pasting from the docs, so I think it's worth fixing.
It would also make sense to use sbt's unified scope syntax (`Universal / mappings` rather than `mappings in Universal`), but let's start with the less controversial things.

remove sbt 0.12 operators from documentation

---

src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemdPlugin.scala
src/sphinx/archetypes/systemloaders.rst

Trying to resolve https://github.com/sbt/sbt-native-packager/issues/1144

Systemd mark file as non config

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/DockerSpotifyClientPlugin.scala

The purpose of this PR is to restore (and adjust) the concurrency tags offered by sbt (https://www.scala-sbt.org/1.x/docs/Parallel-Execution.html) in order to control parallel execution.
By default, sbt tags the "publishLocal" and "publish" tasks with the `Publish` and `Network` tags so that one might limit the number of concurrent tasks competing for resources. 
On a large multi-project, multiple subprojects might be attempting to publishLocal simultaneously (i.e. spin up containers in order to build images) which can exhaust memory available to Docker or cause a longer time to build due to contention on the disk. This PR restores tags on the Docker/publish and Docker/publishLocal tasks so that the user can limit publications and/or image constructions to levels consistent with capacity. …

fix(Docker.*?Plugin): restore the sbt-standard task concurrency tags

---

build.sbt

Resolves #1347 - latest available https://github.com/apache/commons-compress at the point of the PR is https://github.com/apache/commons-compress/tree/rel/1.20

Issue 1347: Upgrade common-compress to 1.20

---

src/sphinx/formats/docker.rst

Fixes #1341 
Since 1.7.1 dockerLayerGrouping is deprecated. 
Rename the setting, and add the correct 'disable' statement.

Describe dockerGroupLayers and how to disable it

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/sbt-test/docker/test-layer-groups/build.sbt
src/sbt-test/docker/test-layer-groups/test

Currently, if a user adds additional artifact to the Docker build
without modifying dockerGroupLayers, the artifact will have "None"
grouping and be put as the first layer in the output.
These additional artifacts are often configuration or supporting
assets. Making this the zeroth layer by default causes dependency
layer to not be re-used if any of these artifacts are changed.
Since not all users will care to modify dockerGroupLayers, the
default should be to make it such that adding additional artifact
does not break re-use of the dependency layer.

docker: make None the last layer group

---

src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala

We're already skipping detection for some Jakarta modules that have legacy `java.*` names. However, there is another source of information - the release notes for Java 11 have [a list](https://www.oracle.com/java/technologies/javase/jdk-11-relnote.html#JDK-8190378) of all removed modules. This PR filters these out as well. Although there is some overlap, I've opted to keep the lists from two sources separate, since the modules are filtered out for different reasons.
Regarding compatibility, this shouldn't impact most builds that use Java 11 and later. For such a build the removed modules could only have come from Jakarta artifacts and such, so they should be present in the project's classpath anyway.

Omit removed Java modules from detected jlinkModules

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

Fixes #1371 
First draft, let me know what you think.
Tested it on my project, it works fine now.

Redirect docker buildkit stderr to info

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/universal/UniversalPlugin.scala

SBT strongly recommends to use the global scope for default settings,
see https://www.scala-sbt.org/1.x/docs/Plugins-Best-Practices.html#Provide+default+values+in
This allows to set the docker image and common labels once in ThisBuild
for all subprojects, and makes it easier to use a different
docker-compatible container builder by overriding the command, e.g.
sbt 'set ThisBuild / dockerExecCommand := Seq("podman")' docker:publish

Move some defaults of docker to global scope

---

src/sphinx/formats/docker.rst

Docs reflect the implementation since it's now based on JavaAppPackaging#projectDependencyArtifacts.
* https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppPackaging.scala#L59
* https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L108

Update dockerGroupLayers documentation

---

src/main/scala/com/typesafe/sbt/packager/Stager.scala

When staging files, only set the target executable permission if the source file is executable and the target file is not executable.
It can be problematic if setting the executable permission on a target file multiple times if using inotify to watch staged files as inotify events will be triggered even when the permission is already set. This fix ensures the executable permission is only set once, to avoid unnecessary inotify events.
I am using development tools to watch the stage directory but currently they get triggered if I run the stage task even when there aren't any changes due to setting the executable permission unnecessarily.
To see this in action, assuming you had an example project with stage script at `example/target/universal/stage/bin/example`  you can run the following to …

Only set executable permission on staged files if required and not set

---

README.md

Unfortunately the Bintray badge on the readme is broken, I guess due to Bintray being [sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)? However, this new Scaladex badge can replace the old Bintray badge - it summarises which versions of sbt are supported by sbt-native-packager (and what the latest sbt-native-packager version is for each of those sbt versions):
[![sbt-native-packager Scala version support](https://index.scala-lang.org/sbt/sbt-native-packager/sbt-native-packager/latest-by-scala-version.svg?targetType=Sbt)](https://index.scala-lang.org/sbt/sbt-native-packager/sbt-native-packager)
More details on the badge format here: https://github.com/scalacenter/scaladex/pull/660 (with some extra changes to better support sbt in …

Replace obsolete Bintray badge with Scaladex version

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/sphinx/formats/docker.rst

Added dockerBuildInit option

---

src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/AshScriptPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala

When generating Unix startup scripts, `scriptClasspath` always uses Unix file separators (`/`). Therefore, `File.separator` cannot be used because the build environment may be on another system (Windows). We must always use Unix file separator when working with Unix paths.
This problem was discovered by me when I tried to build a Linux docker image on Windows. Bash startup script had wrong classpath generated.

Use only Unix file separators when generating Unix scripts

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template

The `realpath` function returns a slightly wrong path for top-level directories. `realpath /root` gives `//root`. This can cause real issues and has led me on a wild goose chase yesterday. (https://github.com/lynxkite/lynxkite/issues/200)
Maybe I should have filed a bug instead of a pull request. I'm not sure this is the best fix. And this same function is repeated in a few places. (`ash-template` in this repo, and another script in the `sbt` repo, at least.) Let me know what's your preference.
Thanks!

Fix for realpath in top-level directories

---

build.sbt

See explanation here: https://github.com/sbt/sbt-native-packager/pull/1442#issuecomment-909040300
Discussion in the scala repo: https://github.com/scala/scala/pull/9743
Same PR for twirl: https://github.com/playframework/twirl/pull/439
BTW I upgraded scala-xml to scala to 1.3.0, the latest release in the 1.x series, which is totally fine here (because we stay on 1.x)
@muuki88 I am pretty sure this needs to be done.

Downgrade scala-parser-combinators

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template

This is the change from #1451 applied to `ash-template`. I don't know much about Ash, but it works on my machine.

Double slash fix for ash-template

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

Some preparations to work on #1417

DockerPlugin code cleanup

---

src/main/scala/com/typesafe/sbt/packager/graalvmnativeimage/GraalVMNativeImagePlugin.scala
src/sphinx/formats/graalvm-native-image.rst

previous fix assumed native-image.cmd from path won't work, but it seems to work fine

use proper native image command on windows

---

src/sphinx/formats/graalvm-native-image.rst

https://www.graalvm.org/22.1/reference-manual/native-image/
The latest of document should be refresh

Fixes link 404 not found

---

project/plugins.sbt

This is to enable usage of sbt-native-packager in Enterprise environments where only the valid-POM format is accepted for JAR downloads, enabling the very powerful sbt-native-packager for thousands of developers.
More background here: https://github.com/esbeetee/sbt-vspp/blob/main/README.md

Add sbt-vspp for publishing the SBT plug-in in a Maven-consistent format

---

build.sbt

There is security vulnerability on common-compress 1.20 ( CVE-2021-35515 ) .
Bump up to 1.21

Bump up commons-compress for security

---

src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala

The previous version had the ":" hard-coded as a `module-path` separator, which might be fine on Linux(es) and Macs, but fails on Windows. I suggest we simply put `File.pathSeparator` instead and rely on the JVM to tell us the right path separator character. Then there is also less burden on this project to keep the path separator code up-to-date.

True Multi OS support with `pathSeparator`

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

See https://github.com/sbt/sbt-native-packager/pull/1527/files#diff-b866751bc91854625b6a5d821ae6a4df02736ceb3581779d81319caee1d9d2cdL278-R289
Error when publishing:
```bash
[error] ERROR: "docker buildx build" requires exactly 1 argument.
[error] See 'docker buildx build --help'.
[error] Usage:  docker buildx build [OPTIONS] PATH | URL | -
[error] Start a build
[error] stack trace is suppressed; run last my-app / Docker / publish for the full output
[error] (my-app / Docker / publish) Nonzero exit value: 1
[error] Total time: 189 s (03:09), completed 17 Jan 2023, 12:33:37 pm
```

Fix bug introduced in #1527

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/CommonStartScriptGenerator.scala
src/sbt-test/docker/multiple-main-classes/build.sbt
src/sbt-test/docker/multiple-main-classes/project/plugins.sbt
src/sbt-test/docker/multiple-main-classes/src/main/scala/Main1.scala
src/sbt-test/docker/multiple-main-classes/src/main/scala/Main2.scala
src/sbt-test/docker/multiple-main-classes/test

This PR adds a script that matches the entrypoint in the Dockerfile. However you will still have to add a `-main` class argument to specify what you actually want to run, as there is no "default main class". 
Example on specify the main class as a parameter
```bash
docker run <your image name> -main com.example.Main2
```
Thanks to @fspillner for the inspiration and 90% of the code :heart:

FIX #1491 DockerPlugin doesn't work with multiple main classes 

---

src/main/scala/com/typesafe/sbt/packager/universal/ZipHelper.scala
src/test/scala/com/typesafe/sbt/packager/universal/ZipHelperSpec.scala

Fixes https://github.com/sbt/sbt-native-packager/issues/1524

Zip helper adds directories

---

src/main/mima-filters/1.3.15.backward.excludes
src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/rpm/pre-template
src/main/resources/com/typesafe/sbt/packager/debian/postinst-template
src/main/resources/com/typesafe/sbt/packager/linux/control-functions
src/main/scala/com/typesafe/sbt/packager/linux/Keys.scala
src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala
src/sbt-test/debian/daemon-user-deb/build.sbt
src/sbt-test/debian/daemon-user-homedir-deb/build.sbt
src/sbt-test/debian/daemon-user-homedir-deb/project/plugins.sbt
src/sbt-test/debian/daemon-user-homedir-deb/test
src/sphinx/archetypes/cheatsheet.rst
src/sphinx/archetypes/java_server/index.rst

resolves #945 
Hi! I recently ran into the same wish as #945 and I had a go at implementing a `daemonHome` setting. 
I've made a best guess at a good default (`var/lib/$user`) as suggested in that issue.
Please take a look!

Create home directory for daemon users in LinuxPlugin

---

src/main/scala/com/typesafe/sbt/packager/graalvmnativeimage/GraalVMNativeImagePlugin.scala

Replace default [BufferedLogger](https://www.scala-sbt.org/1.x/api/sbt/internal/util/BufferedLogger.html) implementation of [ProcessLogger](https://www.scala-lang.org/api/2.12.12/scala/sys/process/ProcessLogger.html) with custom implementation that does not bufferize output - so the stdout of Process come to log immediately, but not at the Process exit

Fixes #1345 - do not buffer logging for native-image output

---

src/main/scala/com/typesafe/sbt/packager/graalvmnativeimage/GraalVMNativeImagePlugin.scala

Fixes #1542 - GraalVMNativeImagePlugin ignores resources in src/graal

---

src/main/scala/com/typesafe/sbt/packager/FileUtil.scala
src/main/scala/com/typesafe/sbt/packager/rpm/RpmHelper.scala
src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala
src/main/scala/com/typesafe/sbt/packager/universal/ZipHelper.scala
src/main/scala/com/typesafe/sbt/packager/windows/WindowsPlugin.scala
src/main/scala/com/typesafe/sbt/packager/windows/WixHelper.scala

SOURCE_DATE_EPOCH is a standardized environment variable that can be set to create reproducbile builds:
https://reproducible-builds.org/docs/source-date-epoch/
If the SOURCE_DATE_EPOCH environment variable is defined, its value is used during the creation of zip, tar, gzip, xz, rpm, and msi files in places where timestamp information is embedded in the resulting file.
To support this capability, a new sourceDateEpoch file utility is added which executes the touch command to set the mtime of the provided file/directory and all children. This utility is called on all source files for the listed packages.
For zip, this also adds the -o option to native zip, and calls setTime() for the non-native zip.
For rpm, this also sets the %use_source_date_epoch_as_buildtime and …

Use SOURCE_DATE_EPOCH for zip, tar, xz, gzip, rpm, msi

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template

sbt-native-packager Java App archetype remote debugging is broken when using `-jvm-debug <port>` in the docker entrypoint. It will start with `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=<port>`, which will terminate the connection prematurely.
Adding the * before the port will allow all remote connections to connect to the debugger port, which was the old default behavior.
See https://bugs.openjdk.org/browse/JDK-8175050

Fixes remote debug connections closing

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bat-template
src/sbt-test/windows/test-bat-template/build.sbt

There are still some things missing for complete parity with the bash script but this gets us a little closer.
I'm using the same logic as [sbt's own launcher](https://github.com/sbt/sbt/blob/2f2a098742a7fcf06d63819162618d5fae976543/launcher-package/src/universal/bin/sbt.bat#L498C83-L518). Unless it starts with `-XX:+` or `-XX:-`, all `-XX:` options are parsed as two arguments
Fixes #1387 
Fixes #1090
Note that if you're using the workaround from #1387 by quoting the options in `application.ini`, that will no longer work.
Used like `-java-home "C:\Program Files\Eclipse Adoptium\jre-11.0.13.8-hotspot"` or `-java-home "%APP_HOME%\jre"`. The argument has higher priority than environment variables.
Fixes #1447
Fixes #1070

Windows bat script improvements

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template

For explanation see comments starting [here](https://github.com/sbt/sbt-native-packager/issues/978#issuecomment-454827566).
Basically we assume ash will only be run in docker images, but never in a cygwin environment.
Currently apps relying on the `is_cygwin` function are broken anyway, so adding this method definitely improves things.

Add `is_cygwin` to ash-template which always returns `false`

---

.github/workflows/validate-pr.yml
src/sbt-test/graalvm-native-image/docker-native-image/build.sbt

`Validate PR / scripted-graavlvm (pull_request)` sometimes fails with this error:
```
Run gu install native-image
Downloading: Release index file from oca.opensource.oracle.com
Internal error occurred: A JSONObject text must begin with '{' at 1 [character 2 line 1]
Error: Process completed with exit code 3.
```
`gu` is the [GraalVM Updater](https://www.graalvm.org/22.0/reference-manual/graalvm-updater/). Add the `--debug` flag to get more info.

Upgrade GraalVM to 22.3.3

---

src/main/mima-filters/1.3.15.backward.excludes
src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/Keys.scala
src/sbt-test/docker/autoremove-multi-stage-intermediate-images/test
src/sphinx/formats/docker.rst

[Docker BuildKit](https://docs.docker.com/build/buildkit) became the default in Docker v23.0 which caused the test to fail. BuildKit doesn't expose intermediate containers as images, so the cleanup setting `dockerAutoremoveMultiStageIntermediateImages` is not relevant when running BuildKit.
I've added a setting `dockerBuildEnvVars` which can be used to disable BuildKit:
```sbt
dockerBuildEnvVars += "DOCKER_BUILDKIT" -> "0"
```
I've also improved BuildKit detection-- it now checks the docker version if `DOCKER_BUILDKIT` is not set.
This incidentally fixes #1518

Add `dockerBuildEnvVars` setting, fix docker test failure in CI

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala
src/sbt-test/ash/command-line-settings/build.sbt
src/sbt-test/ash/command-line-settings/test
src/sbt-test/ash/top-level-main/build.sbt
src/sbt-test/ash/top-level-main/project/build.properties
src/sbt-test/ash/top-level-main/project/plugins.sbt
src/sbt-test/ash/top-level-main/src/main/scala/MainApp.scala
src/sbt-test/ash/top-level-main/test
src/sbt-test/bash/top-level-main/build.sbt
src/sbt-test/bash/top-level-main/project/build.properties
src/sbt-test/bash/top-level-main/project/plugins.sbt
src/sbt-test/bash/top-level-main/src/main/scala/MainApp.scala
src/sbt-test/bash/top-level-main/test

app_mainclass is currently not escaped correctly. This leads to problems in Scala 3 when you define `main` as a function at the top level (as opposed to inside an `object`. In this case, the main class generated by the Scala compiler will contain $ symbols that need to be escaped.
The `LauncherJarPlugin` abuses `mainClass` to set the `-jar foo.jar` parameter instead of a main class, so this case needs to be treated specially (I find this an ugly hack but haven't found a cleaner solution).
The `scripted-docker` test failures seem to be unrelated to my changes as they also occur in [other CI runs](https://github.com/sbt/sbt-native-packager/actions/runs/8395125752)

fix support for top-level `main` methods in Scala 3

---

build.sbt
project/plugins.sbt

Replaces
- #1586
- #1588
- #1584
- #1585
- #1580
- #1571
- #1572
- #1575

Dependency upgrades

---

.github/workflows/publish-site.yml
.github/workflows/release.yml
build.sbt

Fixes #1597
Supersedes #1618
I'm opening this PR from this repository instead of my fork. Hopefully that will fix the permissions issue.

Fix error publishing docs

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
src/sbt-test/ash/command-line-settings/build.sbt

It currently only escapes the first `'` character, but they should all be escaped.
How are shell scripts still a thing in 2024?

fix shellEscape function in ash-template

---

.github/workflows/publish-site.yml
.github/workflows/release.yml
.github/workflows/validate-pr.yml
build.sbt
src/sbt-test/debian/native-build-compress/build.sbt
src/sbt-test/debian/native-build-default/build.sbt

setup-scala is deprecated since setup-java can set up the JDK, and configure the cache.
This brings up the GitHub Actions to a modern set, and collapsing down the duplicated settings for the scripted jobs by using a matrix instead.

ci: Update GitHub Actions to setup-java

---

src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerAntHelper.scala
src/sbt-test/jdkpackager/test-package-image/build.sbt
src/sbt-test/jdkpackager/test-package-image/src/main/scala/ExampleApp.scala
src/sbt-test/jdkpackager/test-package-mappings/build.sbt
src/sbt-test/jdkpackager/test-package-mappings/src/main/scala/ExampleApp.scala
src/sbt-test/jdkpackager/test-package-minimal/build.sbt
src/sbt-test/jdkpackager/test-package-minimal/src/main/scala/ExampleApp.scala
src/sbt-test/jlink/test-jlink-minimal/build.sbt
src/sbt-test/jlink/test-jlink-misc/build.sbt
src/sphinx/formats/jdkpackager.rst
test-project-jdkpackager/build.sbt
test-project-jdkpackager/src/main/scala/ExampleApp.scala

Here's an offshoot from sbt 2.x migration https://github.com/sbt/sbt-native-packager/pull/1647
The unicode arrow is deprecated.
This rewrites it to `=>`.

refactor: Rewrite unicode arrow

---

src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

Multi-platform builds append a `-t` argument for each alias to the `dockerBuildOptions`, but the `publishTask` function was ALWAYS iterating over the aliases even if it was a multi-platform build.
https://github.com/sbt/sbt-native-packager/blob/7c6885910c382784bcd2cd9fc63c2794a9dbd0a2/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L157-L159
The consequence was attempts to buildx and push the tags multiple times. In some environments this leads to build failures because you can't push the same tag twice.
This change simply does not iterate over the aliases for multiplatform builds.
Note: using `dockerUpdateLatest := true` counts as having multiple aliases, which is how I encountered this bug.

Fix multi-platform builds with multiple aliases.

---

LICENSE

As discussed in #1653 sbt-native-packager will adapt the Apache v2 License and no longer require the lightbend CLA to be signed by contributors

Update LICENSE to apache v2

---

LICENSE
LICENSE.md
NOTICE
build.sbt

Remove references to BSD license; add NOTICE file

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-forwarder-template
src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-forwarder-template

Fix #1664
I tested on a personal case but please consider I'm not super experienced in Bash/SH, thus I may be missing a reason for which it wouldn't be the desired behaviour.

🐛 fix: use exec in forwarder scripts (#1664)

---

.scalafmt.conf
src/main/scala/com/typesafe/sbt/PackagerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/FileUtil.scala
src/main/scala/com/typesafe/sbt/packager/SettingsHelper.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BatStartScriptPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemVPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemdPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemloaderPlugin.scala
src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/UpstartPlugin.scala
src/main/scala/com/typesafe/sbt/packager/debian/DebianNativePackaging.scala
src/main/scala/com/typesafe/sbt/packager/debian/DebianPlugin.scala
src/main/scala/com/typesafe/sbt/packager/debian/JDebPackaging.scala
src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/docker/DockerSpotifyClientPlugin.scala
src/main/scala/com/typesafe/sbt/packager/graalvmnativeimage/GraalVMNativeImagePlugin.scala
src/main/scala/com/typesafe/sbt/packager/jar/ClasspathJarPlugin.scala
src/main/scala/com/typesafe/sbt/packager/jar/LauncherJarPlugin.scala
src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerPlugin.scala
src/main/scala/com/typesafe/sbt/packager/linux/LinuxMappingDSL.scala
src/main/scala/com/typesafe/sbt/packager/linux/LinuxPackageMapping.scala
src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala
src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala
src/main/scala/com/typesafe/sbt/packager/universal/UniversalPlugin.scala
src/main/scala/com/typesafe/sbt/packager/windows/WindowsPlugin.scala

fix Scala 3 warnings
```
[warn] -- Warning: /home/runner/work/sbt-native-packager/sbt-native-packager/src/main/scala/com/typesafe/sbt/PackagerPlugin.scala:100:38 
[warn] 100 |    def java_application: Seq[Setting[_]] =
[warn]     |                                      ^
[warn]     |`_` is deprecated for wildcard arguments of types: use `?` instead
[warn]     |This construct can be rewritten automatically under -rewrite -source 3.4-migration.
[warn] -- Warning: /home/runner/work/sbt-native-packager/sbt-native-packager/src/main/scala/com/typesafe/sbt/PackagerPlugin.scala:116:33 
[warn] 116 |    def java_server: Seq[Setting[_]] =
[warn]     |                                 ^
[warn]     |`_` is deprecated for wildcard arguments of types: use `?` instead
[warn]     |This construct can be …
```

Update scalafmt setting. enforce new wildcard syntax

---

src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bat-template
src/sbt-test/windows/test-bat-template/build.sbt

Typical usage is to add it to `conf/application.ini`:
```ini
-Dfile.encoding=UTF-8
-jvm-debug 5005
```

bat script: implement -jvm-debug

---

.github/.scala-steward.conf

SBT 1.x uses Scala 2.12. This should stop scala-steward from opening PRs like #1635 #1610 #1599 to update to Scala 2.13.
This will not affect the updates for Scala 3 / SBT 2.x because that artifact is named `scala3-library`.

scala-steward: pin scala-library to 2.12

---

build.sbt

Currently the CI on Appveyor is failing due to hash in the version number created by back publishing + custom version formatting.
Adjust the formatting to drop back publishing command.

fix: Fix version

---

src/sphinx/formats/universal.rst

Setting needs to be set in the `Compile` configuration, not the `compile` task.

Fix typo in "Skip packageDoc" section
