- src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala
> FIX #482 simple error, nasty solution. Works for the moment, but needs

- src/sbt-test/windows/test-bat-template/build.sbt
it tested on jdk1.7.0_25, jdk1.8.0_20
> fix appveyor test 

- src/sbt-test/jdkpackager/test-package-image/build.sbt
- src/sbt-test/jdkpackager/test-package-image/project/plugins.sbt
- src/sbt-test/jdkpackager/test-package-image/src/main/scala/test/Test.scala
- src/sbt-test/jdkpackager/test-package-image/test
First test for testing launcher generation via JDKPackager.
> Basic image generation detection test for JDKPackagerPlugin.

- src/main/scala/com/typesafe/sbt/packager/rpm/RpmMetadata.scala
- src/main/scala/com/typesafe/sbt/packager/windows/WixHelper.scala
Reverts sbt/sbt-native-packager#524
> Revert "Codacy recommended cleanup."

- src/main/scala/com/typesafe/sbt/packager/rpm/RpmMetadata.scala
- src/main/scala/com/typesafe/sbt/packager/windows/WixHelper.scala
This fixes [Pull Request 524](https://github.com/sbt/sbt-native-packager/pull/524).
[Tests passed](https://ci.appveyor.com/project/myyk/sbt-native-packager/build/3) on Appveyor.
> Codacy fixes

- src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/rpm/postun-template
- use numeric rather than string test in conditional
- add missing semicolon
> fix for issue #529

- src/sphinx/index.rst
in prominent location on front page
> grammar fix for website

- src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala
#597 
Recreated PR with proper branch to fix tar issue
> tar --force-local on windows

- src/sbt-test/rpm/sysvinit-rpm/build.sbt
This test asserts the behaviour added by https://github.com/sbt/sbt-native-packager/pull/661
> Add test for relocatable rpm behaviour

- src/sphinx/archetypes/java_app/my-first-project.rst
> fix typo on document

- src/sphinx/topics/custom.rst
> Add Proguard example to Custom Package Format documentation

- _sources/archetypes/java_app/customize.txt
> Fix minor typo

- archetypes/index.html
Was fixed with PR #739 but reintroduced
> Fix typo (enablePlugis → enablePlugins)

- src/main/scala/com/typesafe/sbt/packager/windows/WindowsPlugin.scala
There was a typo in Windows installer feature title.
> Fix an obvious typo

- src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
> docker: tag -f is deprecated

- src/sphinx/introduction.rst
> concners -> connerns introduction.rst

- src/sphinx/archetypes/systemloaders.rst
`serverAutostart` should actually be `serviceAutostart`
> Updated systemloaders.rst

- src/sbt-test/docker/override-commands/build.sbt
- src/sphinx/formats/docker.rst
> Remove dockerfile/ prefix from openjdk images

- src/main/scala/com/typesafe/sbt/packager/windows/WixHelper.scala
as per https://github.com/sbt/sbt-native-packager/issues/726
> undeprecate generateComponentsAndDirectoryXml in WixHelper

- src/main/scala/com/typesafe/sbt/packager/debian/DebianPlugin.scala
- src/main/scala/com/typesafe/sbt/packager/debian/JDebPackaging.scala
- Add missing dependency in `debian:stage` to `debianConffilesFile`
- Clearly define task dependencies
> Issue 984 depend on conffiles

- src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala
> Preserve executable permissions when creating a tarball

- build.sbt
sbt 1.0.0-RC3 -> 1.0.0
commons-compress 1.4.1 -> 1.14
ant 1.9.6 -> 1.10.1
> Dependency updates:

- .travis.yml
See travis-ci/travis-ci/issues/8408
> Unset JAVA_OPTIONS in travis build

- src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
> Fix dockerVersion command creation

- src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
- src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template
> Remove carriage return characters when loading configuration files.

- src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
Fix https://github.com/sbt/sbt-native-packager/issues/1094
> do not break arguments with spaces inside

- src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-debian-template
- src/sbt-test/debian/sysvinit-deb/build.sbt
> Fix systemv logging

- src/main/scala-sbt-0.13/com/typesafe/sbt/packager/SettingsHelper.scala
- src/main/scala-sbt-1.0/com/typesafe/sbt/packager/SettingsHelper.scala
Fix based on this SO question:
https://stackoverflow.com/questions/47908994/publish-rpm-to-nexus-3/48037275#48037275
> Add scoped resolvers to otherResolvers

- src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
- src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template
based on https://github.com/sbt/sbt-launcher-package/pull/187, tested on OSX from the terminal. Less sure about the ash "fix"
> fixes #1121 

- src/sphinx/introduction.rst
Correct some typos and grammar
> Correct some typos and grammar

- README.md
Fixing Codacy's badge link since it was broken and not showing the image.
> Fix Codacy's badge link

- .travis/download-graalvm
-Update graalvm to version 1.19.0
> Update graalvm installation script

- src/sphinx/archetypes/java_app/index.rst
Added my personal use case into docs, in case someone would try to search for it.
> Mention discoveredMainClasses in documentation

- .travis.yml
- .travis/download-graalvm
- .travis/download-sbt
We could cache GraalVM and sbt for shorter CI time.
> Reuse cache for GraalVM and sbt

- project/plugins.sbt
The workaround was taken from [here](https://github.com/lightbend/mima/issues/422#issuecomment-544861810).
> Add a workaround for lightbend/mima#422

- src/main/scala/com/typesafe/sbt/packager/windows/WindowsPlugin.scala
> WindowsPlugin: add portable WiX support

- src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
- src/sbt-test/docker/file-permission/build.sbt
> Name the main docker stage

- src/sbt-test/docker/simple-sudo-docker/build.sbt
- src/sbt-test/docker/simple-sudo-docker/project/plugins.sbt
- src/sbt-test/docker/simple-sudo-docker/src/main/scala/Main.scala
- src/sbt-test/docker/simple-sudo-docker/test
> Remove docker sudo test from build

- src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
- src/sbt-test/ash/command-line-settings/build.sbt
> Fix argument passing in ash template

- src/sphinx/formats/windows.rst
Addording to current behaviour
> rename task wix-file to wixFile

- README.md
> Restore version in the README to 1.7.4

- src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala
Fixes #1383 
Fixing the order of processing linux mapping files so the conf files are always treated as conf regarless of permission
> Issue 1382: Detect config files regardless of execute permission

- .github/workflows/release.yml
- .github/workflows/validate-pr.yml
Update checkout action. Thanks @igibek
> Fix #1479, #1480, #1481, #1482, #1483, #1484, #1485, #1486, #1487

- src/main/scala/com/typesafe/sbt/packager/graalvmnativeimage/GraalVMNativeImagePlugin.scala
> Specify working directory for graalvm-native-image

- build.sbt
Just trying the obvious thing. Maybe will fix https://github.com/sbt/sbt-native-packager/issues/1513.
> Try updating to scala-xml 2.1.0

- src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template
- src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template
`-agentpath`/`-javaagent` options should go before classpath like `-agentlib`
> handle -agentpath/-javaagent options

- src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template
> require java 8

- build.sbt
https://mvnrepository.com/artifact/com.github.sbt/sbt-native-packager_2.12_1.0/1.9.11
> Upgrade Apache Ant to latest due to CVE.

- README.md
better no version number than a version number nobody remembers to update
> Remove out of date version number from readme

- src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala
- src/sbt-test/docker/file-permission/build.sbt
```
[error]  - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
```
> Fixes FromAsCasing

- build.sbt
Fix the version number while back publishing.
> fix: Fix version number
